SRCS = ORCGN21.CBL \
       ORCGN22.CBL \
       ORCGN23.CBL \
       ORCGN29.CBL \
       ORCGN21ERR.CBL \
       ORCGN21ID1.CBL \
       ORCGN21ID2.CBL \
       ORCGN21FIL.CBL

top_builddir = ../..
include $(top_builddir)/cobol/Makefile.global

