      *******************************************************************
      * Project code name "ORCA"
      * ∆¸∞Â…∏Ω‡•Ï•ª•◊•»•Ω•’•»° JMA standard receipt software°À
      * Copyright(C) 2002 JMA (Japan Medical Association)
      *
      * This program is part of "JMA standard receipt software".
      *
      *     This program is distributed in the hope that it will be useful
      * for further advancement in medical care, according to JMA Open
      * Source License, but WITHOUT ANY WARRANTY.
      *     Everyone is granted permission to use, copy, modify and
      * redistribute this program, but only under the conditions described
      * in the JMA Open Source License. You should have received a copy of
      * this license along with this program. If not, stop using this
      * program and contact JMA, 2-28-16 Honkomagome, Bunkyo-ku, Tokyo,
      * 113-8621, Japan.
      ********************************************************************
      ************************************************************
      *          ∞ÂŒ≈»Ò¿¡µ·ΩÒ COPY (CPRMF100.INC) *
      ************************************************************
      ************************************************************
      *  •≥•‘°º∂ÁΩ§¿µÕ˙ŒÚ
      * Maj/Min/Rev  Ω§¿µº‘       ∆¸…’      ∆‚Õ∆
      *  01.00.01    µ»¿Ó         10/06/07  ƒ¢…ºÕÕº∞§Œ —ππ§À»º§¶Ω§¿µ
      *  01.00.02    «ÎÃÓ         18/11/07  Ω§¿µÕ˙ŒÚ•≥•·•Û•»∫ÔΩ¸
      ************************************************************
           03  MF100-KEY.
      *ø«Œ≈«Ø∑Ó
               05  MF100-SRYYM           PIC  X(06).
      *¿¡µ·•∆°º•÷•Î
           03  MF100-SEIKYU-TBL OCCURS 6.
      *∑ÔøÙ
               05  MF100-KENSU           PIC  9(04).
      *ºıŒŒ∞—«§≥€
               05  MF100-SEIKYUGK        PIC  9(10).
