create	table	tbl_file_info	(
	HOSPNUM	numeric(2,0),
	TBL_KEY	char(8),
	SRYYM	varchar(6),
	SHELLID	varchar(20),
	RENNUM	numeric(3,0),
	SHORI_RENNUM	numeric(3,0),
	SKYYMD	varchar(8),
	TITLE	varchar(100),
	TEISYUTUSAKI	char(1),
	NYUGAIKBN	char(1),
	CNT_ALL	numeric(7,0),
	CNT_NYUIN	numeric(7,0),
	CNT_GAIRAI	numeric(7,0),
	FOR_FOLDER	varchar(200),
	FOR_DATA	varchar(200),
	TO_FOLDER	varchar(200),
	TO_DATA	varchar(200),
	CODE_TYPE	char(1),
	DATA_TYPE	char(1),
	ERR_CODE	char(1),
	ERR_MSG 	varchar(200),
	SYOYMD	varchar(8),
	CREYMD	varchar(8),
	CREHMS	varchar(6),
	primary	key(
		HOSPNUM,
		TBL_KEY,
		SRYYM,
		SHELLID,
		RENNUM,
		SHORI_RENNUM
	)
);
