SRCS = ORCGM97.CBL \
       ORCGMMERR.CBL \
       ORCGMMID1.CBL \
       ORCGM80.CBL \
       ORCGM96.CBL \
       ORCGMJOB.CBL \
       ORCGMGUIDE1.CBL \

top_builddir = ../..
include $(top_builddir)/cobol/Makefile.global

