SRCS = ORCGC02.CBL \
       ORCGC03.CBL \
       ORCGC04.CBL \
       ORCGC05.CBL \
       ORCGC06.CBL \
       ORCGC09.CBL \
       ORCGC10.CBL \
       ORCGC11.CBL \
       ORCGC12.CBL \
       ORCGC99.CBL \
       ORCGCERR.CBL \
       ORCGCID1.CBL \
       ORCGCID2.CBL \
       ORCGCID3.CBL \
       ORCGCID4.CBL \
       ORCGCID5.CBL \
       ORCGCID6.CBL \
       ORAPI022R1V3.CBL \
       ORAPI022R2V3.CBL \

top_builddir = ../..
include $(top_builddir)/cobol/Makefile.global

