CREATE TABLE tbl_henrei_body (
    hospnum smallint NOT NULL,
    teisyutusaki character(1) NOT NULL,
    syoriym character(6) NOT NULL,
    receipt_no character(6) NOT NULL,
    pt_rennum smallint NOT NULL,
    select_flg smallint,
    recesyubetu character(4),
    nyugaikbn character(1),
    sryym character(6),
    name character varying(40),
    sex character(1),
    birthday character(8),
    ptnum character(20),
    ptid bigint,
    hknjanum character(8),
    kigo character varying(40),
    num character varying(40),
    ftnnum_1 character varying(8),
    jkynum_1 character varying(7),
    ftnnum_2 character varying(8),
    jkynum_2 character varying(7),
    ftnnum_3 character varying(8),
    jkynum_3 character varying(7),
    ftnnum_4 character varying(8),
    jkynum_4 character varying(7),
    search_no character varying(30),
    check_no character varying(100),
    hr_code character(5),
    hr_msg character varying(1000),
    henrei_info1 character varying(20),
    henrei_info2 character varying(2200),
    errcd character(3),
    s_syoriymd_1 character(8),
    s_make_flg_1 smallint,
    s_henreiym_1 character(6),
    s_henrei_siji_flg_1 smallint,
    s_teisyutusaki_1 character(1),
    s_nyugaikbn_1 character(1),
    s_receka_1 character(2),
    s_recesyubetu_1 character(4),
    s_hknjanum_1 character(8),
    s_hojokbn_key_1 character(1),
    s_tekstymd_1 character(8),
    s_kigo_1 character varying(40),
    s_syoriymd_2 character(8),
    s_make_flg_2 smallint,
    s_henreiym_2 character(6),
    s_henrei_siji_flg_2 smallint,
    s_teisyutusaki_2 character(1),
    s_nyugaikbn_2 character(1),
    s_receka_2 character(2),
    s_recesyubetu_2 character(4),
    s_hknjanum_2 character(8),
    s_hojokbn_key_2 character(1),
    s_tekstymd_2 character(8),
    s_kigo_2 character varying(40),
    s_syoriymd_3 character(8),
    s_make_flg_3 smallint,
    s_henreiym_3 character(6),
    s_henrei_siji_flg_3 smallint,
    s_teisyutusaki_3 character(1),
    s_nyugaikbn_3 character(1),
    s_receka_3 character(2),
    s_recesyubetu_3 character(4),
    s_hknjanum_3 character(8),
    s_hojokbn_key_3 character(1),
    s_tekstymd_3 character(8),
    s_kigo_3 character varying(40),
    s_syoriymd_4 character(8),
    s_make_flg_4 smallint,
    s_henreiym_4 character(6),
    s_henrei_siji_flg_4 smallint,
    s_teisyutusaki_4 character(1),
    s_nyugaikbn_4 character(1),
    s_receka_4 character(2),
    s_recesyubetu_4 character(4),
    s_hknjanum_4 character(8),
    s_hojokbn_key_4 character(1),
    s_tekstymd_4 character(8),
    s_kigo_4 character varying(40),
    s_syoriymd_5 character(8),
    s_make_flg_5 smallint,
    s_henreiym_5 character(6),
    s_henrei_siji_flg_5 smallint,
    s_teisyutusaki_5 character(1),
    s_nyugaikbn_5 character(1),
    s_receka_5 character(2),
    s_recesyubetu_5 character(4),
    s_hknjanum_5 character(8),
    s_hojokbn_key_5 character(1),
    s_tekstymd_5 character(8),
    s_kigo_5 character varying(40),
    s_syoriymd_6 character(8),
    s_make_flg_6 smallint,
    s_henreiym_6 character(6),
    s_henrei_siji_flg_6 smallint,
    s_teisyutusaki_6 character(1),
    s_nyugaikbn_6 character(1),
    s_receka_6 character(2),
    s_recesyubetu_6 character(4),
    s_hknjanum_6 character(8),
    s_hojokbn_key_6 character(1),
    s_tekstymd_6 character(8),
    s_kigo_6 character varying(40),
    s_syoriymd_7 character(8),
    s_make_flg_7 smallint,
    s_henreiym_7 character(6),
    s_henrei_siji_flg_7 smallint,
    s_teisyutusaki_7 character(1),
    s_nyugaikbn_7 character(1),
    s_receka_7 character(2),
    s_recesyubetu_7 character(4),
    s_hknjanum_7 character(8),
    s_hojokbn_key_7 character(1),
    s_tekstymd_7 character(8),
    s_kigo_7 character varying(40),
    s_syoriymd_8 character(8),
    s_make_flg_8 smallint,
    s_henreiym_8 character(6),
    s_henrei_siji_flg_8 smallint,
    s_teisyutusaki_8 character(1),
    s_nyugaikbn_8 character(1),
    s_receka_8 character(2),
    s_recesyubetu_8 character(4),
    s_hknjanum_8 character(8),
    s_hojokbn_key_8 character(1),
    s_tekstymd_8 character(8),
    s_kigo_8 character varying(40),
    s_syoriymd_9 character(8),
    s_make_flg_9 smallint,
    s_henreiym_9 character(6),
    s_henrei_siji_flg_9 smallint,
    s_teisyutusaki_9 character(1),
    s_nyugaikbn_9 character(1),
    s_receka_9 character(2),
    s_recesyubetu_9 character(4),
    s_hknjanum_9 character(8),
    s_hojokbn_key_9 character(1),
    s_tekstymd_9 character(8),
    s_kigo_9 character varying(40),
    s_syoriymd_10 character(8),
    s_make_flg_10 smallint,
    s_henreiym_10 character(6),
    s_henrei_siji_flg_10 smallint,
    s_teisyutusaki_10 character(1),
    s_nyugaikbn_10 character(1),
    s_receka_10 character(2),
    s_recesyubetu_10 character(4),
    s_hknjanum_10 character(8),
    s_hojokbn_key_10 character(1),
    s_tekstymd_10 character(8),
    s_kigo_10 character varying(40),
    termid character varying(64),
    opid character varying(16),
    creymd character(8),
    upymd character(8),
    uphms character(6),
    s_kohid_key_1 bigint DEFAULT 0,
    s_kohid_key_2 bigint DEFAULT 0,
    s_kohid_key_3 bigint DEFAULT 0,
    s_kohid_key_4 bigint DEFAULT 0,
    s_kohid_key_5 bigint DEFAULT 0,
    s_kohid_key_6 bigint DEFAULT 0,
    s_kohid_key_7 bigint DEFAULT 0,
    s_kohid_key_8 bigint DEFAULT 0,
    s_kohid_key_9 bigint DEFAULT 0,
    s_kohid_key_10 bigint DEFAULT 0,
    teisyutusaki2 character(1) NOT NULL
);

ALTER TABLE ONLY tbl_henrei_body
    ADD CONSTRAINT tbl_henrei_body_primary_key PRIMARY KEY (hospnum, teisyutusaki, teisyutusaki2, syoriym, receipt_no, pt_rennum);

CREATE INDEX idx_henrei_body_kanriinfo ON tbl_henrei_body USING btree (hospnum, check_no);

CREATE INDEX idx_henrei_body_ptid ON tbl_henrei_body USING btree (hospnum, sryym, ptid);

