CREATE TABLE tbl_ptbyomei (
    ptid bigint NOT NULL,
    sryka character(2) NOT NULL,
    sryymd character(8) NOT NULL,
    rennum smallint NOT NULL,
    khnbyomeicd character varying(7),
    byomeiinputcd_1 character varying(20),
    byomeiinputcd_2 character varying(20),
    byomeiinputcd_3 character varying(20),
    byomeiinputcd_4 character varying(20),
    byomeiinputcd_5 character varying(20),
    byomeiinputcd_6 character varying(20),
    byomeicdsu smallint DEFAULT 0,
    byomeicd_1 character varying(7),
    byomeicd_2 character varying(7),
    byomeicd_3 character varying(7),
    byomeicd_4 character varying(7),
    byomeicd_5 character varying(7),
    byomeicd_6 character varying(7),
    byomeicd_7 character varying(7),
    byomeicd_8 character varying(7),
    byomeicd_9 character varying(7),
    byomeicd_10 character varying(7),
    byomeicd_11 character varying(7),
    byomeicd_12 character varying(7),
    byomeicd_13 character varying(7),
    byomeicd_14 character varying(7),
    byomeicd_15 character varying(7),
    byomeicd_16 character varying(7),
    byomeicd_17 character varying(7),
    byomeicd_18 character varying(7),
    byomeicd_19 character varying(7),
    byomeicd_20 character varying(7),
    byomeicd_21 character varying(7),
    utagaiflg character(1),
    syubyoflg character(1),
    manseikbn smallint DEFAULT 0,
    nyugaikbn character(1),
    hkncombi smallint DEFAULT 0,
    rezeflg character(1),
    rezemm smallint DEFAULT 0,
    tenkikbn character(1),
    tenkiymd character varying(8),
    byomei character varying(160),
    byomeimoji smallint DEFAULT 0,
    chartbyomei character varying(160),
    chartbyomeimoji smallint DEFAULT 0,
    byomeihenflg character(1),
    hknbyomeiflg character(1),
    recedenflg character(1),
    hknnum character varying(3),
    khnbuicd_1 character varying(7),
    khnbuicd_2 character varying(7),
    khnbuicd_3 character varying(7),
    dltflg character(1),
    dlt_opid character varying(16),
    termid character varying(16),
    opid character varying(16),
    creymd character(8),
    upymd character(8),
    uphms character(6),
    hospnum smallint NOT NULL,
    seqnum smallint DEFAULT 0,
    hosoku_comment character varying(80),
    hosokucd_1 character varying(20),
    hosokucd_2 character varying(20),
    hosokucd_3 character varying(20)
);

ALTER TABLE ONLY tbl_ptbyomei
    ADD CONSTRAINT tbl_ptbyomei_primary_key PRIMARY KEY (hospnum, ptid, sryka, sryymd, rennum);

