CREATE TABLE tbl_ptnyuinrrk (
    ptid bigint NOT NULL,
    rrknum smallint NOT NULL,
    rrkedanum smallint NOT NULL,
    btunum character(2),
    btuname character varying(20),
    brmnum character(8),
    nyuinka character(2),
    hkncombinum character(4),
    nyuinymd character(8),
    taiinymd character(8),
    taiincd character(2),
    tokutei_kbn character(1),
    tokutei_nyuin character(2),
    rm_sagaku character(2),
    teiki_seikyukbn character(1),
    kensaku_dispkbn character(1),
    shokaikbn character(1),
    shonum smallint,
    drcd1 character(5),
    drcd2 character(5),
    drcd3 character(5),
    jtikbn character(1),
    santei_btunum character(2),
    santei_brmnum character(8),
    tennyuymd character(8),
    tenstuymd character(8),
    taisyonissu integer,
    tusannissu1 integer,
    tusannissu2 integer,
    nyuinchukbn character(1),
    doujitsukbn character(1),
    termid character varying(16),
    opid character varying(16),
    creymd character(8),
    upymd character(8),
    uphms character(6),
    maxedanum smallint,
    skjkbn character(1),
    senteikbn character(1),
    hospnum smallint NOT NULL,
    timekbn_in character(1),
    tainrelkbn character(1),
    kaigokbn character(1),
    nyucalkbn character(1)
);

ALTER TABLE ONLY tbl_ptnyuinrrk
    ADD CONSTRAINT tbl_ptnyuinrrk_primary_key PRIMARY KEY (hospnum, ptid, rrknum, rrkedanum);

