CREATE TABLE tbl_wksryact (
    nyugaikbn character(1) NOT NULL,
    ptid bigint NOT NULL,
    sryka character(2) NOT NULL,
    sryymd character(8) NOT NULL,
    hkncombi smallint NOT NULL,
    zainum integer NOT NULL,
    rennum smallint NOT NULL,
    drcd character(5),
    srysyukbn character(3),
    srykbn character(2),
    jihimoneytotal integer DEFAULT 0,
    srycd_1 character(9),
    srysuryo_1 numeric(10,5) DEFAULT 0,
    srykaisu_1 smallint DEFAULT 0,
    zaikaisu_1 integer DEFAULT 0,
    autokbn_1 character(1),
    inputnum_1 smallint DEFAULT 0,
    inputcoment_1 character varying(80),
    inputchi1_1 character varying(8),
    inputchi1_2 character varying(8),
    inputchi1_3 character varying(8),
    inputchi1_4 character varying(8),
    inputcd_1 character varying(54),
    jihimoney_1 integer DEFAULT 0,
    srycd_2 character(9),
    srysuryo_2 numeric(10,5) DEFAULT 0,
    srykaisu_2 smallint DEFAULT 0,
    zaikaisu_2 integer DEFAULT 0,
    autokbn_2 character(1),
    inputnum_2 smallint DEFAULT 0,
    inputcoment_2 character varying(80),
    inputchi2_1 character varying(8),
    inputchi2_2 character varying(8),
    inputchi2_3 character varying(8),
    inputchi2_4 character varying(8),
    inputcd_2 character varying(54),
    jihimoney_2 integer DEFAULT 0,
    srycd_3 character(9),
    srysuryo_3 numeric(10,5) DEFAULT 0,
    srykaisu_3 smallint DEFAULT 0,
    zaikaisu_3 integer DEFAULT 0,
    autokbn_3 character(1),
    inputnum_3 smallint DEFAULT 0,
    inputcoment_3 character varying(80),
    inputchi3_1 character varying(8),
    inputchi3_2 character varying(8),
    inputchi3_3 character varying(8),
    inputchi3_4 character varying(8),
    inputcd_3 character varying(54),
    jihimoney_3 integer DEFAULT 0,
    srycd_4 character(9),
    srysuryo_4 numeric(10,5) DEFAULT 0,
    srykaisu_4 smallint DEFAULT 0,
    zaikaisu_4 integer DEFAULT 0,
    autokbn_4 character(1),
    inputnum_4 smallint DEFAULT 0,
    inputcoment_4 character varying(80),
    inputchi4_1 character varying(8),
    inputchi4_2 character varying(8),
    inputchi4_3 character varying(8),
    inputchi4_4 character varying(8),
    inputcd_4 character varying(54),
    jihimoney_4 integer DEFAULT 0,
    srycd_5 character(9),
    srysuryo_5 numeric(10,5) DEFAULT 0,
    srykaisu_5 smallint DEFAULT 0,
    zaikaisu_5 integer DEFAULT 0,
    autokbn_5 character(1),
    inputnum_5 smallint DEFAULT 0,
    inputcoment_5 character varying(80),
    inputchi5_1 character varying(8),
    inputchi5_2 character varying(8),
    inputchi5_3 character varying(8),
    inputchi5_4 character varying(8),
    inputcd_5 character varying(54),
    jihimoney_5 integer DEFAULT 0,
    zaitenkei integer DEFAULT 0,
    zaikaikei integer DEFAULT 0,
    syuten1 integer DEFAULT 0,
    syuten2 integer DEFAULT 0,
    ykzten integer DEFAULT 0,
    kizaiten integer DEFAULT 0,
    douji_denpnum integer DEFAULT 0,
    douji_rennum smallint DEFAULT 0,
    contkbn character(1),
    mod_flg smallint DEFAULT 0,
    karte_flg smallint DEFAULT 0,
    karte_key character varying(36),
    termid character varying(16),
    opid character varying(16),
    creymd character(8),
    upymd character(8),
    uphms character(6),
    hospnum smallint NOT NULL,
    inputkbn_1 character(1),
    inputkbn_2 character(1),
    inputkbn_3 character(1),
    inputkbn_4 character(1),
    inputkbn_5 character(1),
    kansuryo_1 numeric(10,5) DEFAULT 0,
    kansuryo_2 numeric(10,5) DEFAULT 0,
    kansuryo_3 numeric(10,5) DEFAULT 0,
    kansuryo_4 numeric(10,5) DEFAULT 0,
    kansuryo_5 numeric(10,5) DEFAULT 0,
    zaikbn smallint DEFAULT 0,
    inputchi1_5 character varying(8),
    inputchi2_5 character varying(8),
    inputchi3_5 character varying(8),
    inputchi4_5 character varying(8),
    inputchi5_5 character varying(8)
);

ALTER TABLE ONLY tbl_wksryact
    ADD CONSTRAINT tbl_wksryact_primary_key PRIMARY KEY (hospnum, nyugaikbn, ptid, sryka, sryymd, hkncombi, zainum, rennum);

