CREATE TABLE tbl_seikyu_koh (
    hospnum smallint NOT NULL,
    sryym integer DEFAULT 0 NOT NULL,
    nyugaikbn character(1) NOT NULL,
    ptid bigint DEFAULT 0 NOT NULL,
    receka character(2) NOT NULL,
    teisyutusaki smallint DEFAULT 0 NOT NULL,
    recesyubetu character(4) NOT NULL,
    hknjanum character(8) NOT NULL,
    hojokbn_key character(1) NOT NULL,
    tekstymd character(8) NOT NULL,
    rennum smallint DEFAULT 0 NOT NULL,
    kohnum character(3),
    kohid smallint DEFAULT 0 NOT NULL,
    jnissu smallint DEFAULT 0,
    tensu1 integer DEFAULT 0,
    tensu2 integer DEFAULT 0,
    tensu3 integer DEFAULT 0,
    tensu4 integer DEFAULT 0,
    tensu5 integer DEFAULT 0,
    tensu6 integer DEFAULT 0,
    tensu7 integer DEFAULT 0,
    tensu8 integer DEFAULT 0,
    tensu9 integer DEFAULT 0,
    tensu10 integer DEFAULT 0,
    tensu11 integer DEFAULT 0,
    tensu12 integer DEFAULT 0,
    tensu13 integer DEFAULT 0,
    tensu14 integer DEFAULT 0,
    tensu15 integer DEFAULT 0,
    tensu16 integer DEFAULT 0,
    tensu17 integer DEFAULT 0,
    tensu18 integer DEFAULT 0,
    tensu19 integer DEFAULT 0,
    tensu20 integer DEFAULT 0,
    tensu21 integer DEFAULT 0,
    tensu22 integer DEFAULT 0,
    tensu23 integer DEFAULT 0,
    tensu24 integer DEFAULT 0,
    tensu25 integer DEFAULT 0,
    tensu26 integer DEFAULT 0,
    tensu27 integer DEFAULT 0,
    tensu28 integer DEFAULT 0,
    tensu29 integer DEFAULT 0,
    tensu30 integer DEFAULT 0,
    tensu31 integer DEFAULT 0,
    tensu32 integer DEFAULT 0,
    tensu33 integer DEFAULT 0,
    tensu34 integer DEFAULT 0,
    tensu35 integer DEFAULT 0,
    tensu36 integer DEFAULT 0,
    tensu37 integer DEFAULT 0,
    tensu38 integer DEFAULT 0,
    tensu39 integer DEFAULT 0,
    tensu40 integer DEFAULT 0,
    tensu41 integer DEFAULT 0,
    tensu42 integer DEFAULT 0,
    tensu43 integer DEFAULT 0,
    tensu44 integer DEFAULT 0,
    tensu45 integer DEFAULT 0,
    totalten integer DEFAULT 0,
    ftnmoney integer DEFAULT 0,
    ftnmoney_ftn integer DEFAULT 0,
    ftnmoney_koj integer DEFAULT 0,
    shokujinissu smallint DEFAULT 0,
    shokujiryoyohi integer DEFAULT 0,
    shokujiftn integer DEFAULT 0,
    ykzftn integer DEFAULT 0,
    kohid_key bigint DEFAULT 0 NOT NULL
);

ALTER TABLE ONLY tbl_seikyu_koh
    ADD CONSTRAINT tbl_seikyu_koh_primary_key PRIMARY KEY (hospnum, sryym, nyugaikbn, ptid, receka, teisyutusaki, recesyubetu, hknjanum, hojokbn_key, kohid_key, tekstymd, rennum);

