CREATE TABLE tbl_lock (
    lock_termid character(64) NOT NULL,
    lock_opid character varying(16),
    locktable_ldname1 character varying(20),
    locktable_ldname2 character varying(20),
    locktable_ldname3 character varying(20),
    locktable_ldname4 character varying(20),
    locktable_ldname5 character varying(20),
    locktable_ldname6 character varying(20),
    locktable_ldname7 character varying(20),
    locktable_ldname8 character varying(20),
    locktable_ldname9 character varying(20),
    locktable_ldname10 character varying(20),
    locktable_ldname11 character varying(20),
    locktable_ldname12 character varying(20),
    locktable_ldname13 character varying(20),
    locktable_ldname14 character varying(20),
    locktable_ldname15 character varying(20),
    locktable_ldname16 character varying(20),
    locktable_ldname17 character varying(20),
    locktable_ldname18 character varying(20),
    locktable_ldname19 character varying(20),
    locktable_ldname20 character varying(20),
    locktable_ldname21 character varying(20),
    locktable_ldname22 character varying(20),
    locktable_ldname23 character varying(20),
    locktable_ldname24 character varying(20),
    locktable_ldname25 character varying(20),
    locktable_ldname26 character varying(20),
    locktable_ldname27 character varying(20),
    locktable_ldname28 character varying(20),
    locktable_ldname29 character varying(20),
    locktable_ldname30 character varying(20),
    locktable_ldname31 character varying(20),
    locktable_ldname32 character varying(20),
    locktable_ldname33 character varying(20),
    locktable_ldname34 character varying(20),
    locktable_ldname35 character varying(20),
    locktable_ldname36 character varying(20),
    locktable_ldname37 character varying(20),
    locktable_ldname38 character varying(20),
    locktable_ldname39 character varying(20),
    locktable_ldname40 character varying(20),
    locktable_ldname41 character varying(20),
    locktable_ldname42 character varying(20),
    locktable_ldname43 character varying(20),
    locktable_ldname44 character varying(20),
    locktable_ldname45 character varying(20),
    locktable_ldname46 character varying(20),
    locktable_ldname47 character varying(20),
    locktable_ldname48 character varying(20),
    locktable_ldname49 character varying(20),
    locktable_ldname50 character varying(20),
    locktable_ptid1 character(10),
    locktable_ptid2 character(10),
    locktable_ptid3 character(10),
    locktable_ptid4 character(10),
    locktable_ptid5 character(10),
    locktable_ptid6 character(10),
    locktable_ptid7 character(10),
    locktable_ptid8 character(10),
    locktable_ptid9 character(10),
    locktable_ptid10 character(10),
    locktable_ptid11 character(10),
    locktable_ptid12 character(10),
    locktable_ptid13 character(10),
    locktable_ptid14 character(10),
    locktable_ptid15 character(10),
    locktable_ptid16 character(10),
    locktable_ptid17 character(10),
    locktable_ptid18 character(10),
    locktable_ptid19 character(10),
    locktable_ptid20 character(10),
    locktable_ptid21 character(10),
    locktable_ptid22 character(10),
    locktable_ptid23 character(10),
    locktable_ptid24 character(10),
    locktable_ptid25 character(10),
    locktable_ptid26 character(10),
    locktable_ptid27 character(10),
    locktable_ptid28 character(10),
    locktable_ptid29 character(10),
    locktable_ptid30 character(10),
    locktable_ptid31 character(10),
    locktable_ptid32 character(10),
    locktable_ptid33 character(10),
    locktable_ptid34 character(10),
    locktable_ptid35 character(10),
    locktable_ptid36 character(10),
    locktable_ptid37 character(10),
    locktable_ptid38 character(10),
    locktable_ptid39 character(10),
    locktable_ptid40 character(10),
    locktable_ptid41 character(10),
    locktable_ptid42 character(10),
    locktable_ptid43 character(10),
    locktable_ptid44 character(10),
    locktable_ptid45 character(10),
    locktable_ptid46 character(10),
    locktable_ptid47 character(10),
    locktable_ptid48 character(10),
    locktable_ptid49 character(10),
    locktable_ptid50 character(10),
    locktable_sryym1 character(8),
    locktable_sryym2 character(8),
    locktable_sryym3 character(8),
    locktable_sryym4 character(8),
    locktable_sryym5 character(8),
    locktable_sryym6 character(8),
    locktable_sryym7 character(8),
    locktable_sryym8 character(8),
    locktable_sryym9 character(8),
    locktable_sryym10 character(8),
    locktable_sryym11 character(8),
    locktable_sryym12 character(8),
    locktable_sryym13 character(8),
    locktable_sryym14 character(8),
    locktable_sryym15 character(8),
    locktable_sryym16 character(8),
    locktable_sryym17 character(8),
    locktable_sryym18 character(8),
    locktable_sryym19 character(8),
    locktable_sryym20 character(8),
    locktable_sryym21 character(8),
    locktable_sryym22 character(8),
    locktable_sryym23 character(8),
    locktable_sryym24 character(8),
    locktable_sryym25 character(8),
    locktable_sryym26 character(8),
    locktable_sryym27 character(8),
    locktable_sryym28 character(8),
    locktable_sryym29 character(8),
    locktable_sryym30 character(8),
    locktable_sryym31 character(8),
    locktable_sryym32 character(8),
    locktable_sryym33 character(8),
    locktable_sryym34 character(8),
    locktable_sryym35 character(8),
    locktable_sryym36 character(8),
    locktable_sryym37 character(8),
    locktable_sryym38 character(8),
    locktable_sryym39 character(8),
    locktable_sryym40 character(8),
    locktable_sryym41 character(8),
    locktable_sryym42 character(8),
    locktable_sryym43 character(8),
    locktable_sryym44 character(8),
    locktable_sryym45 character(8),
    locktable_sryym46 character(8),
    locktable_sryym47 character(8),
    locktable_sryym48 character(8),
    locktable_sryym49 character(8),
    locktable_sryym50 character(8),
    locktable_startdate1 character(8),
    locktable_startdate2 character(8),
    locktable_startdate3 character(8),
    locktable_startdate4 character(8),
    locktable_startdate5 character(8),
    locktable_startdate6 character(8),
    locktable_startdate7 character(8),
    locktable_startdate8 character(8),
    locktable_startdate9 character(8),
    locktable_startdate10 character(8),
    locktable_startdate11 character(8),
    locktable_startdate12 character(8),
    locktable_startdate13 character(8),
    locktable_startdate14 character(8),
    locktable_startdate15 character(8),
    locktable_startdate16 character(8),
    locktable_startdate17 character(8),
    locktable_startdate18 character(8),
    locktable_startdate19 character(8),
    locktable_startdate20 character(8),
    locktable_startdate21 character(8),
    locktable_startdate22 character(8),
    locktable_startdate23 character(8),
    locktable_startdate24 character(8),
    locktable_startdate25 character(8),
    locktable_startdate26 character(8),
    locktable_startdate27 character(8),
    locktable_startdate28 character(8),
    locktable_startdate29 character(8),
    locktable_startdate30 character(8),
    locktable_startdate31 character(8),
    locktable_startdate32 character(8),
    locktable_startdate33 character(8),
    locktable_startdate34 character(8),
    locktable_startdate35 character(8),
    locktable_startdate36 character(8),
    locktable_startdate37 character(8),
    locktable_startdate38 character(8),
    locktable_startdate39 character(8),
    locktable_startdate40 character(8),
    locktable_startdate41 character(8),
    locktable_startdate42 character(8),
    locktable_startdate43 character(8),
    locktable_startdate44 character(8),
    locktable_startdate45 character(8),
    locktable_startdate46 character(8),
    locktable_startdate47 character(8),
    locktable_startdate48 character(8),
    locktable_startdate49 character(8),
    locktable_startdate50 character(8),
    locktable_enddate1 character(8),
    locktable_enddate2 character(8),
    locktable_enddate3 character(8),
    locktable_enddate4 character(8),
    locktable_enddate5 character(8),
    locktable_enddate6 character(8),
    locktable_enddate7 character(8),
    locktable_enddate8 character(8),
    locktable_enddate9 character(8),
    locktable_enddate10 character(8),
    locktable_enddate11 character(8),
    locktable_enddate12 character(8),
    locktable_enddate13 character(8),
    locktable_enddate14 character(8),
    locktable_enddate15 character(8),
    locktable_enddate16 character(8),
    locktable_enddate17 character(8),
    locktable_enddate18 character(8),
    locktable_enddate19 character(8),
    locktable_enddate20 character(8),
    locktable_enddate21 character(8),
    locktable_enddate22 character(8),
    locktable_enddate23 character(8),
    locktable_enddate24 character(8),
    locktable_enddate25 character(8),
    locktable_enddate26 character(8),
    locktable_enddate27 character(8),
    locktable_enddate28 character(8),
    locktable_enddate29 character(8),
    locktable_enddate30 character(8),
    locktable_enddate31 character(8),
    locktable_enddate32 character(8),
    locktable_enddate33 character(8),
    locktable_enddate34 character(8),
    locktable_enddate35 character(8),
    locktable_enddate36 character(8),
    locktable_enddate37 character(8),
    locktable_enddate38 character(8),
    locktable_enddate39 character(8),
    locktable_enddate40 character(8),
    locktable_enddate41 character(8),
    locktable_enddate42 character(8),
    locktable_enddate43 character(8),
    locktable_enddate44 character(8),
    locktable_enddate45 character(8),
    locktable_enddate46 character(8),
    locktable_enddate47 character(8),
    locktable_enddate48 character(8),
    locktable_enddate49 character(8),
    locktable_enddate50 character(8),
    locktable_starttime1 character(8),
    locktable_starttime2 character(8),
    locktable_starttime3 character(8),
    locktable_starttime4 character(8),
    locktable_starttime5 character(8),
    locktable_starttime6 character(8),
    locktable_starttime7 character(8),
    locktable_starttime8 character(8),
    locktable_starttime9 character(8),
    locktable_starttime10 character(8),
    locktable_starttime11 character(8),
    locktable_starttime12 character(8),
    locktable_starttime13 character(8),
    locktable_starttime14 character(8),
    locktable_starttime15 character(8),
    locktable_starttime16 character(8),
    locktable_starttime17 character(8),
    locktable_starttime18 character(8),
    locktable_starttime19 character(8),
    locktable_starttime20 character(8),
    locktable_starttime21 character(8),
    locktable_starttime22 character(8),
    locktable_starttime23 character(8),
    locktable_starttime24 character(8),
    locktable_starttime25 character(8),
    locktable_starttime26 character(8),
    locktable_starttime27 character(8),
    locktable_starttime28 character(8),
    locktable_starttime29 character(8),
    locktable_starttime30 character(8),
    locktable_starttime31 character(8),
    locktable_starttime32 character(8),
    locktable_starttime33 character(8),
    locktable_starttime34 character(8),
    locktable_starttime35 character(8),
    locktable_starttime36 character(8),
    locktable_starttime37 character(8),
    locktable_starttime38 character(8),
    locktable_starttime39 character(8),
    locktable_starttime40 character(8),
    locktable_starttime41 character(8),
    locktable_starttime42 character(8),
    locktable_starttime43 character(8),
    locktable_starttime44 character(8),
    locktable_starttime45 character(8),
    locktable_starttime46 character(8),
    locktable_starttime47 character(8),
    locktable_starttime48 character(8),
    locktable_starttime49 character(8),
    locktable_starttime50 character(8),
    locktable_endtime1 character(8),
    locktable_endtime2 character(8),
    locktable_endtime3 character(8),
    locktable_endtime4 character(8),
    locktable_endtime5 character(8),
    locktable_endtime6 character(8),
    locktable_endtime7 character(8),
    locktable_endtime8 character(8),
    locktable_endtime9 character(8),
    locktable_endtime10 character(8),
    locktable_endtime11 character(8),
    locktable_endtime12 character(8),
    locktable_endtime13 character(8),
    locktable_endtime14 character(8),
    locktable_endtime15 character(8),
    locktable_endtime16 character(8),
    locktable_endtime17 character(8),
    locktable_endtime18 character(8),
    locktable_endtime19 character(8),
    locktable_endtime20 character(8),
    locktable_endtime21 character(8),
    locktable_endtime22 character(8),
    locktable_endtime23 character(8),
    locktable_endtime24 character(8),
    locktable_endtime25 character(8),
    locktable_endtime26 character(8),
    locktable_endtime27 character(8),
    locktable_endtime28 character(8),
    locktable_endtime29 character(8),
    locktable_endtime30 character(8),
    locktable_endtime31 character(8),
    locktable_endtime32 character(8),
    locktable_endtime33 character(8),
    locktable_endtime34 character(8),
    locktable_endtime35 character(8),
    locktable_endtime36 character(8),
    locktable_endtime37 character(8),
    locktable_endtime38 character(8),
    locktable_endtime39 character(8),
    locktable_endtime40 character(8),
    locktable_endtime41 character(8),
    locktable_endtime42 character(8),
    locktable_endtime43 character(8),
    locktable_endtime44 character(8),
    locktable_endtime45 character(8),
    locktable_endtime46 character(8),
    locktable_endtime47 character(8),
    locktable_endtime48 character(8),
    locktable_endtime49 character(8),
    locktable_endtime50 character(8),
    locktable_flg1 character(1),
    locktable_flg2 character(1),
    locktable_flg3 character(1),
    locktable_flg4 character(1),
    locktable_flg5 character(1),
    locktable_flg6 character(1),
    locktable_flg7 character(1),
    locktable_flg8 character(1),
    locktable_flg9 character(1),
    locktable_flg10 character(1),
    locktable_flg11 character(1),
    locktable_flg12 character(1),
    locktable_flg13 character(1),
    locktable_flg14 character(1),
    locktable_flg15 character(1),
    locktable_flg16 character(1),
    locktable_flg17 character(1),
    locktable_flg18 character(1),
    locktable_flg19 character(1),
    locktable_flg20 character(1),
    locktable_flg21 character(1),
    locktable_flg22 character(1),
    locktable_flg23 character(1),
    locktable_flg24 character(1),
    locktable_flg25 character(1),
    locktable_flg26 character(1),
    locktable_flg27 character(1),
    locktable_flg28 character(1),
    locktable_flg29 character(1),
    locktable_flg30 character(1),
    locktable_flg31 character(1),
    locktable_flg32 character(1),
    locktable_flg33 character(1),
    locktable_flg34 character(1),
    locktable_flg35 character(1),
    locktable_flg36 character(1),
    locktable_flg37 character(1),
    locktable_flg38 character(1),
    locktable_flg39 character(1),
    locktable_flg40 character(1),
    locktable_flg41 character(1),
    locktable_flg42 character(1),
    locktable_flg43 character(1),
    locktable_flg44 character(1),
    locktable_flg45 character(1),
    locktable_flg46 character(1),
    locktable_flg47 character(1),
    locktable_flg48 character(1),
    locktable_flg49 character(1),
    locktable_flg50 character(1),
    hospnum numeric(2,0) NOT NULL
);

ALTER TABLE ONLY tbl_lock
    ADD CONSTRAINT tbl_lock_primary_key PRIMARY KEY (hospnum, lock_termid);

