CREATE TABLE tbl_syunou_nyuin (
    nyugaikbn character(1) NOT NULL,
    ptid bigint NOT NULL,
    denpnum integer NOT NULL,
    roomnum character(8),
    byotonum character(2),
    rmsagaku integer,
    rmsagaku_tax_sai integer,
    shokuji1_nissu smallint,
    shokuji1 integer,
    shokuji2_nissu smallint,
    shokuji2 integer,
    shokuji3_nissu smallint,
    shokuji3 integer,
    shokuji4_nissu smallint,
    shokuji4 integer,
    shokuji5_nissu smallint,
    shokuji5 integer,
    shokuji6_nissu smallint,
    shokuji6 integer,
    shokuji7_nissu smallint,
    shokuji7 integer,
    syuskj_nissu smallint,
    syuskj_ryoyohi integer,
    syuskj_ftn integer,
    syuskj_ftn_rece integer,
    syuskj_ftnkbn character(1),
    koh1skj_nissu smallint,
    koh1skj_ryoyohi integer,
    koh1skj_ftn integer,
    koh1skj_ftn_rece integer,
    koh1skj_ftnkbn character(1),
    koh2skj_nissu smallint,
    koh2skj_ryoyohi integer,
    koh2skj_ftn integer,
    koh2skj_ftn_rece integer,
    koh2skj_ftnkbn character(1),
    koh3skj_nissu smallint,
    koh3skj_ryoyohi integer,
    koh3skj_ftn integer,
    koh3skj_ftn_rece integer,
    koh3skj_ftnkbn character(1),
    koh4skj_nissu smallint,
    koh4skj_ryoyohi integer,
    koh4skj_ftn integer,
    koh4skj_ftn_rece integer,
    koh4skj_ftnkbn character(1),
    ryoyohi_skj integer,
    skymoney_skj integer,
    skymoney_skj_tax integer,
    skymoney_skj_kei integer,
    ryoyohi_skj_jihi integer,
    skymoney_skj_jihi integer,
    skymoney_skj_jihi_tax integer,
    skymoney_skj_jihi_kei integer,
    day_1 character(1),
    day_2 character(1),
    day_3 character(1),
    day_4 character(1),
    day_5 character(1),
    day_6 character(1),
    day_7 character(1),
    day_8 character(1),
    day_9 character(1),
    day_10 character(1),
    day_11 character(1),
    day_12 character(1),
    day_13 character(1),
    day_14 character(1),
    day_15 character(1),
    day_16 character(1),
    day_17 character(1),
    day_18 character(1),
    day_19 character(1),
    day_20 character(1),
    day_21 character(1),
    day_22 character(1),
    day_23 character(1),
    day_24 character(1),
    day_25 character(1),
    day_26 character(1),
    day_27 character(1),
    day_28 character(1),
    day_29 character(1),
    day_30 character(1),
    day_31 character(1),
    nyuin_rrknum smallint,
    shokuji8_nissu smallint DEFAULT 0,
    shokuji8 integer DEFAULT 0,
    shokuji9_nissu smallint DEFAULT 0,
    shokuji9 integer DEFAULT 0,
    shokuji10_nissu smallint DEFAULT 0,
    shokuji10 integer DEFAULT 0,
    ryoyohi_life integer DEFAULT 0,
    skymoney_life integer DEFAULT 0,
    skymoney_life_tax integer DEFAULT 0,
    skymoney_life_kei integer DEFAULT 0,
    ryoyohi_life_jihi integer DEFAULT 0,
    skymoney_life_jihi integer DEFAULT 0,
    skymoney_life_jihi_tax integer DEFAULT 0,
    skymoney_life_jihi_kei integer DEFAULT 0,
    hospnum smallint NOT NULL
);

ALTER TABLE ONLY tbl_syunou_nyuin
    ADD CONSTRAINT tbl_syunou_nyuin_primary_key PRIMARY KEY (hospnum, nyugaikbn, ptid, denpnum);

