CREATE TABLE tbl_tensu (
    srycd character(9) NOT NULL,
    yukostymd character(8) NOT NULL,
    yukoedymd character(8) NOT NULL,
    srykbn character(2),
    srysyukbn character(3),
    yukoketa smallint DEFAULT 0,
    name character varying(200),
    kanayukoketa smallint DEFAULT 0,
    kananame character varying(200),
    formalyukoketa smallint DEFAULT 0,
    formalname character varying(400),
    tensikibetu smallint DEFAULT 0,
    ten numeric(11,2) DEFAULT 0,
    tanicd character(3),
    tanimojisu smallint DEFAULT 0,
    taniname character varying(24),
    datakbn smallint DEFAULT 0,
    hkntekkbn smallint DEFAULT 0,
    nyugaitekkbn smallint DEFAULT 0,
    routekkbn smallint DEFAULT 0,
    hospsrykbn smallint DEFAULT 0,
    osinkbn smallint DEFAULT 0,
    houksnkbn smallint DEFAULT 0,
    byokanrenkbn smallint DEFAULT 0,
    sdokanryo smallint DEFAULT 0,
    jituday smallint DEFAULT 0,
    daycnt smallint DEFAULT 0,
    ykzknrkbn smallint DEFAULT 0,
    kzmcompsikibetu smallint DEFAULT 0,
    kzmkgn integer DEFAULT 0,
    kzmjgn integer DEFAULT 0,
    kzm integer DEFAULT 0,
    kzmten numeric(9,2) DEFAULT 0,
    kzmerr smallint DEFAULT 0,
    jgncnt smallint DEFAULT 0,
    jgncnt1d smallint DEFAULT 0,
    jgncnt1w smallint DEFAULT 0,
    jgncntetcm smallint DEFAULT 0,
    jgncntetc smallint DEFAULT 0,
    jgncnterr smallint DEFAULT 0,
    chuksncd character(4),
    chuksntsuban character(1),
    tsusokuage smallint DEFAULT 0,
    kgnage character(2),
    jgnage character(2),
    timeksnkbn smallint DEFAULT 0,
    kijunteigenkbn smallint DEFAULT 0,
    kijunteigencd smallint DEFAULT 0,
    laserksn smallint DEFAULT 0,
    chpmesuksn smallint DEFAULT 0,
    micmesuksn smallint DEFAULT 0,
    donorkbn smallint DEFAULT 0,
    knsjiskbn smallint DEFAULT 0,
    knsjisgrpkbn smallint DEFAULT 0,
    teigenkbn smallint DEFAULT 0,
    sekizuisokutei smallint DEFAULT 0,
    keibujyutu smallint DEFAULT 0,
    autohougo smallint DEFAULT 0,
    gaikanrikbn smallint DEFAULT 0,
    tusokugaikbn smallint DEFAULT 0,
    hokatuteigenkbn smallint DEFAULT 0,
    chpnaisiksn smallint DEFAULT 0,
    autofungo smallint DEFAULT 0,
    chiikiksn smallint DEFAULT 0,
    byosyokbn smallint DEFAULT 0,
    chpgyokosotiksn smallint DEFAULT 0,
    shortstayope smallint DEFAULT 0,
    buikbn smallint DEFAULT 0,
    santeirrkkbn smallint DEFAULT 0,
    sstkijuncd1 smallint DEFAULT 0,
    sstkijuncd2 smallint DEFAULT 0,
    sstkijuncd3 smallint DEFAULT 0,
    sstkijuncd4 smallint DEFAULT 0,
    sstkijuncd5 smallint DEFAULT 0,
    sstkijuncd6 smallint DEFAULT 0,
    sstkijuncd7 smallint DEFAULT 0,
    sstkijuncd8 smallint DEFAULT 0,
    sstkijuncd9 smallint DEFAULT 0,
    sstkijuncd10 smallint DEFAULT 0,
    ageksnkgn1 character(2),
    ageksnjgn1 character(2),
    ageksnsrycd1 character varying(9),
    ageksnkgn2 character(2),
    ageksnjgn2 character(2),
    ageksnsrycd2 character varying(9),
    ageksnkgn3 character(2),
    ageksnjgn3 character(2),
    ageksnsrycd3 character varying(9),
    ageksnkgn4 character(2),
    ageksnjgn4 character(2),
    ageksnsrycd4 character varying(9),
    kentaicomment smallint DEFAULT 0,
    nyukhnkbn smallint DEFAULT 0,
    nyukhnksnkbn smallint DEFAULT 0,
    kangoksn smallint DEFAULT 0,
    oldtenskb smallint DEFAULT 0,
    oldten numeric(11,2) DEFAULT 0,
    madokukbn smallint DEFAULT 0,
    sinkeihakaikbn smallint DEFAULT 0,
    seibutugakukbn smallint DEFAULT 0,
    zoeizaikbn smallint DEFAULT 0,
    csyyouryo integer DEFAULT 0,
    ykzkbn smallint DEFAULT 0,
    zaigatakbn smallint DEFAULT 0,
    kouhatukbn smallint DEFAULT 0,
    longtoyokbn smallint DEFAULT 0,
    meiuseskb smallint DEFAULT 0,
    tokukizaiageksnkbn smallint DEFAULT 0,
    sansokbn smallint DEFAULT 0,
    tokukizaisbt1 smallint DEFAULT 0,
    tokukizaisbt2 smallint DEFAULT 0,
    jgnten integer DEFAULT 0,
    gaitenttlkbn smallint DEFAULT 0,
    nyutenttlkbn smallint DEFAULT 0,
    cdkbn_kbn character(1),
    cdkbn_syo smallint DEFAULT 0,
    cdkbn_bu smallint DEFAULT 0,
    cdkbn_kbnnum smallint DEFAULT 0,
    cdkbn_kbnnum_eda smallint DEFAULT 0,
    cdkbn_kouban smallint DEFAULT 0,
    kokuchi_kbn character(1),
    kokuchi_syo smallint DEFAULT 0,
    kokuchi_bu smallint DEFAULT 0,
    kokuchi_kbnnum smallint DEFAULT 0,
    kokuchi_kbnnum_eda smallint DEFAULT 0,
    kokuchi_kouban smallint DEFAULT 0,
    kokujiskbkbn1 smallint DEFAULT 0,
    kokujiskbkbn2 smallint DEFAULT 0,
    namechgkbn smallint DEFAULT 0,
    kananamechgkbn smallint DEFAULT 0,
    idokanren character varying(9),
    kouhyojyunnum integer DEFAULT 0,
    yakkakjncd character varying(12),
    syusaiskb smallint DEFAULT 0,
    syomeikanren character varying(9),
    chgymd character varying(8),
    haisiymd character varying(8),
    keikasochiymd character varying(8),
    termid character varying(16),
    opid character varying(16),
    creymd character(8),
    upymd character(8),
    uphms character(6),
    hospnum smallint NOT NULL,
    gazoopesup smallint DEFAULT 0,
    iryokansatukbn smallint DEFAULT 0,
    masuiskbkbn smallint DEFAULT 0
);

ALTER TABLE ONLY tbl_tensu
    ADD CONSTRAINT tbl_tensu_primary_key PRIMARY KEY (hospnum, srycd, yukostymd, yukoedymd);

CREATE INDEX idx_tensu_formalname ON tbl_tensu USING btree (formalname);

CREATE INDEX idx_tensu_kananame ON tbl_tensu USING btree (kananame);

CREATE INDEX idx_tensu_kensagrp ON tbl_tensu USING btree (hospnum, srykbn, knsjisgrpkbn);

CREATE INDEX idx_tensu_name ON tbl_tensu USING btree (name);

