CREATE TABLE tbl_seikyu_etc (
    hospnum smallint DEFAULT 0 NOT NULL,
    sryym integer DEFAULT 0 NOT NULL,
    nyugaikbn character(1) NOT NULL,
    ptid bigint DEFAULT 0 NOT NULL,
    receka character(2) NOT NULL,
    teisyutusaki smallint DEFAULT 0 NOT NULL,
    recesyubetu character(4) NOT NULL,
    hknjanum character(8) NOT NULL,
    hojokbn_key character(1) NOT NULL,
    tekstymd character(8) NOT NULL,
    etc_kohnum1 character(3) DEFAULT ''::bpchar,
    etc_kohnum2 character(3) DEFAULT ''::bpchar,
    etc_kohnum3 character(3) DEFAULT ''::bpchar,
    etc_kohnum4 character(3) DEFAULT ''::bpchar,
    etc_jnissu1 smallint DEFAULT 0,
    etc_jnissu2 smallint DEFAULT 0,
    etc_jnissu3 smallint DEFAULT 0,
    etc_jnissu4 smallint DEFAULT 0,
    etc_totalten1 integer DEFAULT 0,
    etc_totalten2 integer DEFAULT 0,
    etc_totalten3 integer DEFAULT 0,
    etc_totalten4 integer DEFAULT 0,
    etc_ftnmoney1 integer DEFAULT 0,
    etc_ftnmoney_ftn1 integer DEFAULT 0,
    etc_ftnmoney_koj1 integer DEFAULT 0,
    etc_ftnmoney2 integer DEFAULT 0,
    etc_ftnmoney_ftn2 integer DEFAULT 0,
    etc_ftnmoney_koj2 integer DEFAULT 0,
    etc_ftnmoney3 integer DEFAULT 0,
    etc_ftnmoney_ftn3 integer DEFAULT 0,
    etc_ftnmoney_koj3 integer DEFAULT 0,
    etc_ftnmoney4 integer DEFAULT 0,
    etc_ftnmoney_ftn4 integer DEFAULT 0,
    etc_ftnmoney_koj4 integer DEFAULT 0,
    etc_ykzftn1 integer DEFAULT 0,
    etc_ykzftn2 integer DEFAULT 0,
    etc_ykzftn3 integer DEFAULT 0,
    etc_ykzftn4 integer DEFAULT 0,
    etc_shokujinissu1 smallint DEFAULT 0,
    etc_shokujiryoyohi1 integer DEFAULT 0,
    etc_shokujiftn1 integer DEFAULT 0,
    etc_shokujinissu2 smallint DEFAULT 0,
    etc_shokujiryoyohi2 integer DEFAULT 0,
    etc_shokujiftn2 integer DEFAULT 0,
    etc_shokujinissu3 smallint DEFAULT 0,
    etc_shokujiryoyohi3 integer DEFAULT 0,
    etc_shokujiftn3 integer DEFAULT 0,
    etc_shokujinissu4 smallint DEFAULT 0,
    etc_shokujiryoyohi4 integer DEFAULT 0,
    etc_shokujiftn4 integer DEFAULT 0,
    kohid_key bigint DEFAULT 0 NOT NULL
);

ALTER TABLE ONLY tbl_seikyu_etc
    ADD CONSTRAINT tbl_seikyu_etc_primary_key PRIMARY KEY (hospnum, sryym, nyugaikbn, ptid, receka, teisyutusaki, recesyubetu, hknjanum, hojokbn_key, kohid_key, tekstymd);

