CREATE TABLE tbl_hkncombi (
    ptid bigint NOT NULL,
    hkncombinum smallint NOT NULL,
    hknid bigint,
    hknnum character(3),
    honkzkkbn character(1),
    hojokbn character(1),
    contkbn character(1),
    koh1id bigint,
    koh1hknnum character(3),
    koh1paykbn character(2),
    koh2id bigint,
    koh2hknnum character(3),
    koh2paykbn character(2),
    koh3id bigint,
    koh3hknnum character(3),
    koh3paykbn character(2),
    koh4id bigint,
    koh4hknnum character(3),
    koh4paykbn character(2),
    tekstymd character(8),
    tekedymd character(8),
    syu_tanseidoname character varying(40),
    syu_hknkohsbtkbn character(1),
    syu_gaijgnkbn character(1),
    syu_nyujgnkbn character(1),
    koh1_tanseidoname character varying(20),
    koh1_hknkohsbtkbn character(1),
    koh1_gaijgnkbn character(1),
    koh1_nyujgnkbn character(1),
    koh2_tanseidoname character varying(20),
    koh2_hknkohsbtkbn character(1),
    koh2_gaijgnkbn character(1),
    koh2_nyujgnkbn character(1),
    koh3_tanseidoname character varying(20),
    koh3_hknkohsbtkbn character(1),
    koh3_gaijgnkbn character(1),
    koh3_nyujgnkbn character(1),
    koh4_tanseidoname character varying(20),
    koh4_hknkohsbtkbn character(1),
    koh4_gaijgnkbn character(1),
    koh4_nyujgnkbn character(1),
    gai_ftnkbn character(1),
    gai_kftnrate smallint DEFAULT 0,
    gai_kkotgak integer DEFAULT 0,
    gai_kjgngak integer DEFAULT 0,
    gai_djgngak integer DEFAULT 0,
    gai_djgncnt smallint DEFAULT 0,
    gai_mnaijgngak integer DEFAULT 0,
    gai_mgaijgngak integer DEFAULT 0,
    gai_mjgncnt smallint DEFAULT 0,
    gai_ykzftnkbn character(1),
    nyu_ftnkbn character(1),
    nyu_kftnrate smallint DEFAULT 0,
    nyu_kkotgak integer DEFAULT 0,
    nyu_kjgngak integer DEFAULT 0,
    nyu_djgngak integer DEFAULT 0,
    nyu_djgncnt smallint DEFAULT 0,
    nyu_mjgngak integer DEFAULT 0,
    nyu_mjgncnt smallint DEFAULT 0,
    nyu_skjryokbn character(1),
    tsy_gaiftnkbn character(1),
    tsy_gaikftnrate smallint DEFAULT 0,
    tsy_gaikkotgak integer DEFAULT 0,
    tsy_gaikjgngak integer DEFAULT 0,
    tsy_gaidjgngak integer DEFAULT 0,
    tsy_gaidjgncnt smallint DEFAULT 0,
    tsy_gaimnaijgngak integer DEFAULT 0,
    tsy_gaimgaijgngak integer DEFAULT 0,
    tsy_gaimjgncnt smallint DEFAULT 0,
    tsy_gaiykzftnkbn character(1),
    tsy_nyuftnkbn character(1),
    tsy_nyukftnrate smallint DEFAULT 0,
    tsy_nyukkotgak integer DEFAULT 0,
    tsy_nyukjgngak integer DEFAULT 0,
    tsy_nyudjgngak integer DEFAULT 0,
    tsy_nyudjgncnt smallint DEFAULT 0,
    tsy_nyumjgngak integer DEFAULT 0,
    tsy_nyumjgncnt smallint DEFAULT 0,
    tsy_nyuskjryokbn character(1),
    tnk_gaiftnkbn character(1),
    tnk_gaikftnrate smallint DEFAULT 0,
    tnk_gaikkotgak integer DEFAULT 0,
    tnk_gaikjgngak integer DEFAULT 0,
    tnk_gaidjgngak integer DEFAULT 0,
    tnk_gaidjgncnt smallint DEFAULT 0,
    tnk_gaimnaijgngak integer DEFAULT 0,
    tnk_gaimgaijgngak integer DEFAULT 0,
    tnk_gaimjgncnt smallint DEFAULT 0,
    tnk_gaiykzftnkbn character(1),
    tnk_nyuftnkbn character(1),
    tnk_nyukftnrate smallint DEFAULT 0,
    tnk_nyukkotgak integer DEFAULT 0,
    tnk_nyukjgngak integer DEFAULT 0,
    tnk_nyudjgngak integer DEFAULT 0,
    tnk_nyudjgncnt smallint DEFAULT 0,
    tnk_nyumjgngak integer DEFAULT 0,
    tnk_nyumjgncnt smallint DEFAULT 0,
    tnk_nyuskjryokbn character(1),
    tentnk smallint DEFAULT 0,
    taxkbn character(1),
    chgkbn character(1),
    delkbn character(1),
    termid character varying(16),
    opid character varying(16),
    creymd character(8),
    upymd character(8),
    uphms character(6),
    hospnum smallint NOT NULL,
    hyojikbn character(1)
);

ALTER TABLE ONLY tbl_hkncombi
    ADD CONSTRAINT tbl_hkncombi_primary_key PRIMARY KEY (hospnum, ptid, hkncombinum);

