CREATE TABLE tbl_ldmap (
    map_ldname character varying(20) NOT NULL,
    map_groupnum numeric(2,0),
    map_edanum numeric(2,0),
    map_ldmsg character varying(20),
    map_dsp_flg numeric(1,0),
    map_haita_flg numeric(1,0),
    map_termid character varying(64),
    map_opid character varying(16),
    ldmap_chk_ldname1 character varying(20),
    ldmap_chk_ldname2 character varying(20),
    ldmap_chk_ldname3 character varying(20),
    ldmap_chk_ldname4 character varying(20),
    ldmap_chk_ldname5 character varying(20),
    ldmap_chk_ldname6 character varying(20),
    ldmap_chk_ldname7 character varying(20),
    ldmap_chk_ldname8 character varying(20),
    ldmap_chk_ldname9 character varying(20),
    ldmap_chk_ldname10 character varying(20),
    ldmap_chk_ldname11 character varying(20),
    ldmap_chk_ldname12 character varying(20),
    ldmap_chk_ldname13 character varying(20),
    ldmap_chk_ldname14 character varying(20),
    ldmap_chk_ldname15 character varying(20),
    ldmap_chk_ldname16 character varying(20),
    ldmap_chk_ldname17 character varying(20),
    ldmap_chk_ldname18 character varying(20),
    ldmap_chk_ldname19 character varying(20),
    ldmap_chk_ldname20 character varying(20),
    ldmap_chk_ldname21 character varying(20),
    ldmap_chk_ldname22 character varying(20),
    ldmap_chk_ldname23 character varying(20),
    ldmap_chk_ldname24 character varying(20),
    ldmap_chk_ldname25 character varying(20),
    ldmap_chk_ldname26 character varying(20),
    ldmap_chk_ldname27 character varying(20),
    ldmap_chk_ldname28 character varying(20),
    ldmap_chk_ldname29 character varying(20),
    ldmap_chk_ldname30 character varying(20),
    ldmap_chk_ldname31 character varying(20),
    ldmap_chk_ldname32 character varying(20),
    ldmap_chk_ldname33 character varying(20),
    ldmap_chk_ldname34 character varying(20),
    ldmap_chk_ldname35 character varying(20),
    ldmap_chk_ldname36 character varying(20),
    ldmap_chk_ldname37 character varying(20),
    ldmap_chk_ldname38 character varying(20),
    ldmap_chk_ldname39 character varying(20),
    ldmap_chk_ldname40 character varying(20),
    ldmap_chk_ldname41 character varying(20),
    ldmap_chk_ldname42 character varying(20),
    ldmap_chk_ldname43 character varying(20),
    ldmap_chk_ldname44 character varying(20),
    ldmap_chk_ldname45 character varying(20),
    ldmap_chk_ldname46 character varying(20),
    ldmap_chk_ldname47 character varying(20),
    ldmap_chk_ldname48 character varying(20),
    ldmap_chk_ldname49 character varying(20),
    ldmap_chk_ldname50 character varying(20),
    hospnum numeric(2,0) NOT NULL
);

ALTER TABLE ONLY tbl_ldmap
    ADD CONSTRAINT tbl_ldmap_primary_key PRIMARY KEY (hospnum, map_ldname);

