CREATE TABLE tbl_bunben (
    hospnum smallint NOT NULL,
    ptid bigint DEFAULT 0 NOT NULL,
    skyym character(6) NOT NULL,
    rrknum integer DEFAULT 0 NOT NULL,
    ptnum character(20) NOT NULL,
    skykbn character(1) NOT NULL,
    riyoukbn character(1) NOT NULL,
    bunbenkbn character(1) NOT NULL,
    teisyutusaki character(1) NOT NULL,
    kanyukbn character(1) NOT NULL,
    honkzkkbn character(1) NOT NULL,
    hknjanum character(8) NOT NULL,
    kigo character varying(40) NOT NULL,
    num character varying(40) NOT NULL,
    name character varying(40) NOT NULL,
    zaiweek smallint DEFAULT 0 NOT NULL,
    birthday character(8) NOT NULL,
    sizankbn character(1) NOT NULL,
    birthcnt smallint DEFAULT 0 NOT NULL,
    nyuin_day smallint DEFAULT 0 NOT NULL,
    sankakbn character(1) NOT NULL,
    nyu_money integer DEFAULT 0,
    rmsgk_money integer DEFAULT 0,
    kaijo_money integer DEFAULT 0,
    bunben_money integer DEFAULT 0,
    shin_money integer DEFAULT 0,
    kns_money integer DEFAULT 0,
    syc_money integer DEFAULT 0,
    snk_money integer DEFAULT 0,
    etc_money integer DEFAULT 0,
    icbftn_money integer DEFAULT 0,
    ninpuftn_money integer DEFAULT 0,
    dairi_money integer DEFAULT 0,
    bikou character varying(60) NOT NULL,
    updkbn character(1) NOT NULL,
    hknjanum_s character(8) NOT NULL,
    termid character varying(16),
    opid character varying(16),
    creymd character(8),
    upymd character(8),
    uphms character(6),
    teisyutubikbn character(1),
    nyugaikbn character(1) NOT NULL
);

ALTER TABLE ONLY tbl_bunben
    ADD CONSTRAINT tbl_bunben_primary_key PRIMARY KEY (hospnum, ptid, nyugaikbn, skyym, rrknum);

