\set ON_ERROR_STOP

CREATE TABLE tbl_syunou_new (
    nyugaikbn character(1) NOT NULL,
    ptid numeric(10,0) NOT NULL,
    denpnum integer NOT NULL,
    denplastnum smallint,
    sryka character(2),
    sryymd character(8),
    denpjtikbn character(1),
    createkbn character(1),
    denpprtymd character(8),
    skystymd character(8),
    skyedymd character(8),
    hkncombinum character(4),
    syuhknnum character(3),
    syuhknftnmoney integer,
    syucompftn integer,
    syucompftn_entani numeric(8,1),
    syucompykzftn integer,
    syucomptotal integer,
    syuykzftnkbn character(1),
    koh1hknnum character(3),
    koh1hknftnmoney integer,
    koh1compftn integer,
    koh1compftn_entani numeric(8,1),
    koh1compykzftn integer,
    koh1comptotal integer,
    koh1ykzftnkbn character(1),
    koh2hknnum character(3),
    koh2hknftnmoney integer,
    koh2compftn integer,
    koh2compftn_entani numeric(8,1),
    koh2compykzftn integer,
    koh2comptotal integer,
    koh2ykzftnkbn character(1),
    koh3hknnum character(3),
    koh3hknftnmoney integer,
    koh3compftn integer,
    koh3compftn_entani numeric(8,1),
    koh3compykzftn integer,
    koh3comptotal integer,
    koh3ykzftnkbn character(1),
    koh4hknnum character(3),
    koh4hknftnmoney integer,
    koh4compftn integer,
    koh4compftn_entani numeric(8,1),
    koh4compykzftn integer,
    koh4comptotal integer,
    koh4ykzftnkbn character(1),
    ptftnrate smallint,
    roomnum character(8),
    byotonum character(2),
    skykukbn character(1),
    tax_taishou integer,
    tax_money integer,
    skygk integer,
    ssu_hknten integer,
    ssu_money integer,
    ssu_tgmoney integer,
    ssu_tgmoney_tax integer,
    sdo_hknten integer,
    sdo_money integer,
    sdo_tgmoney integer,
    sdo_tgmoney_tax integer,
    ztk_hknten integer,
    ztk_money integer,
    ztk_tgmoney integer,
    ztk_tgmoney_tax integer,
    tyk_hknten integer,
    tyk_money integer,
    tyk_tgmoney integer,
    tyk_tgmoney_tax integer,
    csy_hknten integer,
    csy_money integer,
    csy_tgmoney integer,
    csy_tgmoney_tax integer,
    syc_hknten integer,
    syc_money integer,
    syc_tgmoney integer,
    syc_tgmoney_tax integer,
    sjt_hknten integer,
    sjt_money integer,
    sjt_tgmoney integer,
    sjt_tgmoney_tax integer,
    kns_hknten integer,
    kns_money integer,
    kns_tgmoney integer,
    kns_tgmoney_tax integer,
    gzu_hknten integer,
    gzu_money integer,
    gzu_tgmoney integer,
    gzu_tgmoney_tax integer,
    etc_hknten integer,
    etc_money integer,
    etc_tgmoney integer,
    etc_tgmoney_tax integer,
    nyn_hknten integer,
    nyn_money integer,
    nyn_tgmoney integer,
    nyn_tgmoney_tax integer,
    total_hknten integer,
    total_money integer,
    total_tgmoney integer,
    total_tgmoney_tax integer,
    tgmoney_tax_sai integer,
    jihi_1 integer,
    jihi_1_tax integer,
    jihi_2 integer,
    jihi_2_tax integer,
    jihi_3 integer,
    jihi_3_tax integer,
    jihi_4 integer,
    jihi_4_tax integer,
    jihi_5 integer,
    jihi_5_tax integer,
    jihi_6 integer DEFAULT 0,
    jihi_6_tax integer DEFAULT 0,
    jihi_7 integer DEFAULT 0,
    jihi_7_tax integer DEFAULT 0,
    jihi_8 integer DEFAULT 0,
    jihi_8_tax integer DEFAULT 0,
    jihi_9 integer DEFAULT 0,
    jihi_9_tax integer DEFAULT 0,
    jihi_10 integer DEFAULT 0,
    jihi_10_tax integer DEFAULT 0,
    jihi_total integer,
    jihi_total_tax integer,
    jihi_tax integer,
    rjn_ftn integer,
    koh_ftn integer,
    koh_ftn_entani numeric(8,1),
    ykz_ftn integer,
    rese_ykz_ftn integer,
    kohtaiykzkbn character(1),
    chosei integer,
    grp_denpnum integer,
    grp_rennum smallint,
    grp_sgkmoney integer,
    secmoney integer,
    hkntekmoney integer,
    discount_kbn character(2),
    discount_body character varying(160),
    discount_ratekbn character(2),
    discount_teiritu character(1),
    discount_rate integer,
    discount_money integer DEFAULT 0,
    rsishoshin_money integer,
    rsisaishin_money integer,
    rsisdo_money integer,
    rsietc_money integer,
    rsi_tax_sai integer,
    rsi_total integer,
    rsijibai_skymoney integer,
    skymoney_tax_sai integer,
    skymoney integer,
    nyukin_total integer,
    nyukin_kaisu integer,
    misyuriyu character(2),
    drcd character(5),
    nynshokaisu smallint,
    ykzkennum integer,
    rmsagaku integer,
    rmsagaku_tax_sai integer,
    shokuji1_nissu smallint,
    shokuji1 integer,
    shokuji2_nissu smallint,
    shokuji2 integer,
    shokuji3_nissu smallint,
    shokuji3 integer,
    shokuji4_nissu smallint,
    shokuji4 integer,
    shokuji5_nissu smallint,
    shokuji5 integer,
    shokuji6_nissu smallint,
    shokuji6 integer,
    shokuji7_nissu smallint,
    shokuji7 integer,
    syuskj_nissu smallint,
    syuskj_ryoyohi integer,
    syuskj_ftn integer,
    syuskj_ftn_rece integer,
    syuskj_ftnkbn character(1),
    koh1skj_nissu smallint,
    koh1skj_ryoyohi integer,
    koh1skj_ftn integer,
    koh1skj_ftn_rece integer,
    koh1skj_ftnkbn character(1),
    koh2skj_nissu smallint,
    koh2skj_ryoyohi integer,
    koh2skj_ftn integer,
    koh2skj_ftn_rece integer,
    koh2skj_ftnkbn character(1),
    koh3skj_nissu smallint,
    koh3skj_ryoyohi integer,
    koh3skj_ftn integer,
    koh3skj_ftn_rece integer,
    koh3skj_ftnkbn character(1),
    koh4skj_nissu smallint,
    koh4skj_ryoyohi integer,
    koh4skj_ftn integer,
    koh4skj_ftn_rece integer,
    koh4skj_ftnkbn character(1),
    ryoyohi_skj integer,
    skymoney_skj integer,
    skymoney_skj_tax integer,
    skymoney_skj_kei integer,
    ryoyohi_skj_jihi integer,
    skymoney_skj_jihi integer,
    skymoney_skj_jihi_tax integer,
    skymoney_skj_jihi_kei integer,
    skj_ftngaku1 integer,
    skj_ftnday1 smallint,
    skj_ftngaku2 integer,
    skj_ftnday2 smallint,
    skj_ftngaku3 integer,
    skj_ftnday3 smallint,
    saikeisankbn character(1),
    ingaishohokbn character(1),
    douji_denpnum integer,
    contkbn character(1),
    day_1 character(1),
    day_2 character(1),
    day_3 character(1),
    day_4 character(1),
    day_5 character(1),
    day_6 character(1),
    day_7 character(1),
    day_8 character(1),
    day_9 character(1),
    day_10 character(1),
    day_11 character(1),
    day_12 character(1),
    day_13 character(1),
    day_14 character(1),
    day_15 character(1),
    day_16 character(1),
    day_17 character(1),
    day_18 character(1),
    day_19 character(1),
    day_20 character(1),
    day_21 character(1),
    day_22 character(1),
    day_23 character(1),
    day_24 character(1),
    day_25 character(1),
    day_26 character(1),
    day_27 character(1),
    day_28 character(1),
    day_29 character(1),
    day_30 character(1),
    day_31 character(1),
    fuku_denpnum integer,
    fuku_kbn character(1),
    zaitaku character(1),
    kyufugai_shoshin_ten integer,
    kyufugai_sidou_ten integer,
    kyufugai_osin1_ten integer,
    kyufugai_osin2_ten integer,
    kyufugai_osin3_ten integer,
    kyufugai_gokei_ten integer,
    dayinfflg character(1),
    nyuin_rrknum smallint,
    acct_updkbn character(1),
    jyo_hknftnmoney integer DEFAULT 0,
    jyo_compftn integer DEFAULT 0,
    jyo_compftn_entani numeric(8,1) DEFAULT 0,
    termid character varying(16),
    opid character varying(16),
    creymd character(8),
    upymd character(8),
    uphms character(6),
    msi_hknten integer DEFAULT 0,
    msi_money integer DEFAULT 0,
    msi_tgmoney integer DEFAULT 0,
    msi_tgmoney_tax integer DEFAULT 0,
    ssn_hknten integer DEFAULT 0,
    ssn_money integer DEFAULT 0,
    ssn_tgmoney integer DEFAULT 0,
    ssn_tgmoney_tax integer DEFAULT 0,
    hou_hknten integer DEFAULT 0,
    hou_money integer DEFAULT 0,
    hou_tgmoney integer DEFAULT 0,
    hou_tgmoney_tax integer DEFAULT 0,
    ryo_hknten integer DEFAULT 0,
    ryo_money integer DEFAULT 0,
    ryo_tgmoney integer DEFAULT 0,
    ryo_tgmoney_tax integer DEFAULT 0,
    shohou_sai integer DEFAULT 0,
    grp_hakhouflg smallint DEFAULT 0,
    shokuji8_nissu smallint DEFAULT 0,
    shokuji8 integer DEFAULT 0,
    shokuji9_nissu smallint DEFAULT 0,
    shokuji9 integer DEFAULT 0,
    shokuji10_nissu smallint DEFAULT 0,
    shokuji10 integer DEFAULT 0,
    ryoyohi_life integer DEFAULT 0,
    skymoney_life integer DEFAULT 0,
    skymoney_life_tax integer DEFAULT 0,
    skymoney_life_kei integer DEFAULT 0,
    ryoyohi_life_jihi integer DEFAULT 0,
    skymoney_life_jihi integer DEFAULT 0,
    skymoney_life_jihi_tax integer DEFAULT 0,
    skymoney_life_jihi_kei integer DEFAULT 0,
    hospnum smallint NOT NULL,
    byr_hknten integer DEFAULT 0,
    byr_money integer DEFAULT 0,
    byr_tgmoney integer DEFAULT 0,
    byr_tgmoney_tax integer DEFAULT 0
);

INSERT INTO tbl_syunou_new select * from tbl_syunou;

drop table tbl_syunou;

alter table tbl_syunou_new rename to tbl_syunou;

ALTER TABLE ONLY tbl_syunou
    ADD CONSTRAINT tbl_syunou_primary_key PRIMARY KEY (hospnum, nyugaikbn, ptid, denpnum);

CREATE INDEX idx_syunou_ptid ON tbl_syunou USING btree (hospnum, ptid);

