\set ON_ERROR_STOP

CREATE TABLE tbl_syunou_main (
    nyugaikbn character(1) NOT NULL,
    ptid bigint NOT NULL,
    denpnum integer NOT NULL,
    denplastnum smallint,
    sryka character(2),
    sryymd character(8),
    denpjtikbn character(1),
    createkbn character(1),
    denpprtymd character(8),
    skystymd character(8),
    skyedymd character(8),
    hkncombinum character(4),
    syuhknnum character(3),
    syuhknftnmoney integer,
    syucompftn integer,
    syucompftn_entani numeric(8,1),
    syucompykzftn integer,
    syucomptotal integer,
    syuykzftnkbn character(1),
    koh1hknnum character(3),
    koh1hknftnmoney integer,
    koh1compftn integer,
    koh1compftn_entani numeric(8,1),
    koh1compykzftn integer,
    koh1comptotal integer,
    koh1ykzftnkbn character(1),
    koh2hknnum character(3),
    koh2hknftnmoney integer,
    koh2compftn integer,
    koh2compftn_entani numeric(8,1),
    koh2compykzftn integer,
    koh2comptotal integer,
    koh2ykzftnkbn character(1),
    koh3hknnum character(3),
    koh3hknftnmoney integer,
    koh3compftn integer,
    koh3compftn_entani numeric(8,1),
    koh3compykzftn integer,
    koh3comptotal integer,
    koh3ykzftnkbn character(1),
    koh4hknnum character(3),
    koh4hknftnmoney integer,
    koh4compftn integer,
    koh4compftn_entani numeric(8,1),
    koh4compykzftn integer,
    koh4comptotal integer,
    koh4ykzftnkbn character(1),
    ptftnrate smallint,
    skykukbn character(1),
    tax_taishou integer,
    tax_money integer,
    skygk integer,
    ssu_hknten integer,
    ssu_money integer,
    ssu_tgmoney integer,
    ssu_tgmoney_tax integer,
    sdo_hknten integer,
    sdo_money integer,
    sdo_tgmoney integer,
    sdo_tgmoney_tax integer,
    ztk_hknten integer,
    ztk_money integer,
    ztk_tgmoney integer,
    ztk_tgmoney_tax integer,
    tyk_hknten integer,
    tyk_money integer,
    tyk_tgmoney integer,
    tyk_tgmoney_tax integer,
    csy_hknten integer,
    csy_money integer,
    csy_tgmoney integer,
    csy_tgmoney_tax integer,
    syc_hknten integer,
    syc_money integer,
    syc_tgmoney integer,
    syc_tgmoney_tax integer,
    sjt_hknten integer,
    sjt_money integer,
    sjt_tgmoney integer,
    sjt_tgmoney_tax integer,
    kns_hknten integer,
    kns_money integer,
    kns_tgmoney integer,
    kns_tgmoney_tax integer,
    gzu_hknten integer,
    gzu_money integer,
    gzu_tgmoney integer,
    gzu_tgmoney_tax integer,
    etc_hknten integer,
    etc_money integer,
    etc_tgmoney integer,
    etc_tgmoney_tax integer,
    nyn_hknten integer,
    nyn_money integer,
    nyn_tgmoney integer,
    nyn_tgmoney_tax integer,
    total_hknten integer,
    total_money integer,
    total_tgmoney integer,
    total_tgmoney_tax integer,
    tgmoney_tax_sai integer,
    jihi_1 integer,
    jihi_1_tax integer,
    jihi_2 integer,
    jihi_2_tax integer,
    jihi_3 integer,
    jihi_3_tax integer,
    jihi_4 integer,
    jihi_4_tax integer,
    jihi_5 integer,
    jihi_5_tax integer,
    jihi_6 integer DEFAULT 0,
    jihi_6_tax integer DEFAULT 0,
    jihi_7 integer DEFAULT 0,
    jihi_7_tax integer DEFAULT 0,
    jihi_8 integer DEFAULT 0,
    jihi_8_tax integer DEFAULT 0,
    jihi_9 integer DEFAULT 0,
    jihi_9_tax integer DEFAULT 0,
    jihi_10 integer DEFAULT 0,
    jihi_10_tax integer DEFAULT 0,
    jihi_total integer,
    jihi_total_tax integer,
    jihi_tax integer,
    rjn_ftn integer,
    koh_ftn integer,
    koh_ftn_entani numeric(8,1),
    ykz_ftn integer,
    rese_ykz_ftn integer,
    kohtaiykzkbn character(1),
    chosei integer,
    grp_denpnum integer,
    grp_rennum smallint,
    grp_sgkmoney integer,
    secmoney integer,
    hkntekmoney integer,
    discount_kbn character(2),
    discount_body character varying(160),
    discount_ratekbn character(2),
    discount_teiritu character(1),
    discount_rate integer,
    discount_money integer DEFAULT 0,
    rsishoshin_money integer,
    rsisaishin_money integer,
    rsisdo_money integer,
    rsietc_money integer,
    rsi_tax_sai integer,
    rsi_total integer,
    rsijibai_skymoney integer,
    skymoney_tax_sai integer,
    skymoney integer,
    nyukin_total integer,
    nyukin_kaisu integer,
    misyuriyu character(2),
    drcd character(5),
    nynshokaisu smallint,
    ykzkennum integer,
    skj_ftngaku1 integer,
    skj_ftnday1 smallint,
    skj_ftngaku2 integer,
    skj_ftnday2 smallint,
    skj_ftngaku3 integer,
    skj_ftnday3 smallint,
    saikeisankbn character(1),
    ingaishohokbn character(1),
    douji_denpnum integer,
    contkbn character(1),
    fuku_denpnum integer,
    fuku_kbn character(1),
    zaitaku character(1),
    kyufugai_shoshin_ten integer,
    kyufugai_sidou_ten integer,
    kyufugai_osin1_ten integer,
    kyufugai_osin2_ten integer,
    kyufugai_osin3_ten integer,
    kyufugai_gokei_ten integer,
    dayinfflg character(1),
    acct_updkbn character(1),
    jyo_hknftnmoney integer DEFAULT 0,
    jyo_compftn integer DEFAULT 0,
    jyo_compftn_entani numeric(8,1) DEFAULT 0,
    termid character varying(16),
    opid character varying(16),
    creymd character(8),
    upymd character(8),
    uphms character(6),
    msi_hknten integer DEFAULT 0,
    msi_money integer DEFAULT 0,
    msi_tgmoney integer DEFAULT 0,
    msi_tgmoney_tax integer DEFAULT 0,
    ssn_hknten integer DEFAULT 0,
    ssn_money integer DEFAULT 0,
    ssn_tgmoney integer DEFAULT 0,
    ssn_tgmoney_tax integer DEFAULT 0,
    hou_hknten integer DEFAULT 0,
    hou_money integer DEFAULT 0,
    hou_tgmoney integer DEFAULT 0,
    hou_tgmoney_tax integer DEFAULT 0,
    ryo_hknten integer DEFAULT 0,
    ryo_money integer DEFAULT 0,
    ryo_tgmoney integer DEFAULT 0,
    ryo_tgmoney_tax integer DEFAULT 0,
    shohou_sai integer DEFAULT 0,
    grp_hakhouflg smallint DEFAULT 0,
    hospnum smallint NOT NULL,
    byr_hknten integer DEFAULT 0,
    byr_money integer DEFAULT 0,
    byr_tgmoney integer DEFAULT 0,
    byr_tgmoney_tax integer DEFAULT 0,
    skynyukinkbn character(1)
);

insert into tbl_syunou_main (
nyugaikbn,
ptid,
denpnum,
denplastnum,
sryka,
sryymd,
denpjtikbn,
createkbn,
denpprtymd,
skystymd,
skyedymd,
hkncombinum,
syuhknnum,
syuhknftnmoney,
syucompftn,
syucompftn_entani,
syucompykzftn,
syucomptotal,
syuykzftnkbn,
koh1hknnum,
koh1hknftnmoney,
koh1compftn,
koh1compftn_entani,
koh1compykzftn,
koh1comptotal,
koh1ykzftnkbn,
koh2hknnum,
koh2hknftnmoney,
koh2compftn,
koh2compftn_entani,
koh2compykzftn,
koh2comptotal,
koh2ykzftnkbn,
koh3hknnum,
koh3hknftnmoney,
koh3compftn,
koh3compftn_entani,
koh3compykzftn,
koh3comptotal,
koh3ykzftnkbn,
koh4hknnum,
koh4hknftnmoney,
koh4compftn,
koh4compftn_entani,
koh4compykzftn,
koh4comptotal,
koh4ykzftnkbn,
ptftnrate,
skykukbn,
tax_taishou,
tax_money,
skygk,
ssu_hknten,
ssu_money,
ssu_tgmoney,
ssu_tgmoney_tax,
sdo_hknten,
sdo_money,
sdo_tgmoney,
sdo_tgmoney_tax,
ztk_hknten,
ztk_money,
ztk_tgmoney,
ztk_tgmoney_tax,
tyk_hknten,
tyk_money,
tyk_tgmoney,
tyk_tgmoney_tax,
csy_hknten,
csy_money,
csy_tgmoney,
csy_tgmoney_tax,
syc_hknten,
syc_money,
syc_tgmoney,
syc_tgmoney_tax,
sjt_hknten,
sjt_money,
sjt_tgmoney,
sjt_tgmoney_tax,
kns_hknten,
kns_money,
kns_tgmoney,
kns_tgmoney_tax,
gzu_hknten,
gzu_money,
gzu_tgmoney,
gzu_tgmoney_tax,
etc_hknten,
etc_money,
etc_tgmoney,
etc_tgmoney_tax,
nyn_hknten,
nyn_money,
nyn_tgmoney,
nyn_tgmoney_tax,
total_hknten,
total_money,
total_tgmoney,
total_tgmoney_tax,
tgmoney_tax_sai,
jihi_1,
jihi_1_tax,
jihi_2,
jihi_2_tax,
jihi_3,
jihi_3_tax,
jihi_4,
jihi_4_tax,
jihi_5,
jihi_5_tax,
jihi_6,
jihi_6_tax,
jihi_7,
jihi_7_tax,
jihi_8,
jihi_8_tax,
jihi_9,
jihi_9_tax,
jihi_10,
jihi_10_tax,
jihi_total,
jihi_total_tax,
jihi_tax,
rjn_ftn,
koh_ftn,
koh_ftn_entani,
ykz_ftn,
rese_ykz_ftn,
kohtaiykzkbn,
chosei,
grp_denpnum,
grp_rennum,
grp_sgkmoney,
secmoney,
hkntekmoney,
discount_kbn,
discount_body,
discount_ratekbn,
discount_teiritu,
discount_rate,
discount_money,
rsishoshin_money,
rsisaishin_money,
rsisdo_money,
rsietc_money,
rsi_tax_sai,
rsi_total,
rsijibai_skymoney,
skymoney_tax_sai,
skymoney,
nyukin_total,
nyukin_kaisu,
misyuriyu,
drcd,
nynshokaisu,
ykzkennum,
skj_ftngaku1,
skj_ftnday1,
skj_ftngaku2,
skj_ftnday2,
skj_ftngaku3,
skj_ftnday3,
saikeisankbn,
ingaishohokbn,
douji_denpnum,
contkbn,
fuku_denpnum,
fuku_kbn,
zaitaku,
kyufugai_shoshin_ten,
kyufugai_sidou_ten,
kyufugai_osin1_ten,
kyufugai_osin2_ten,
kyufugai_osin3_ten,
kyufugai_gokei_ten,
dayinfflg,
acct_updkbn,
jyo_hknftnmoney,
jyo_compftn,
jyo_compftn_entani,
termid,
opid,
creymd,
upymd,
uphms,
msi_hknten,
msi_money,
msi_tgmoney,
msi_tgmoney_tax,
ssn_hknten,
ssn_money,
ssn_tgmoney,
ssn_tgmoney_tax,
hou_hknten,
hou_money,
hou_tgmoney,
hou_tgmoney_tax,
ryo_hknten,
ryo_money,
ryo_tgmoney,
ryo_tgmoney_tax,
shohou_sai,
grp_hakhouflg,
hospnum,
byr_hknten,
byr_money,
byr_tgmoney,
byr_tgmoney_tax,
skynyukinkbn
)
select
nyugaikbn,
ptid,
denpnum,
denplastnum,
sryka,
sryymd,
denpjtikbn,
createkbn,
denpprtymd,
skystymd,
skyedymd,
hkncombinum,
syuhknnum,
syuhknftnmoney,
syucompftn,
syucompftn_entani,
syucompykzftn,
syucomptotal,
syuykzftnkbn,
koh1hknnum,
koh1hknftnmoney,
koh1compftn,
koh1compftn_entani,
koh1compykzftn,
koh1comptotal,
koh1ykzftnkbn,
koh2hknnum,
koh2hknftnmoney,
koh2compftn,
koh2compftn_entani,
koh2compykzftn,
koh2comptotal,
koh2ykzftnkbn,
koh3hknnum,
koh3hknftnmoney,
koh3compftn,
koh3compftn_entani,
koh3compykzftn,
koh3comptotal,
koh3ykzftnkbn,
koh4hknnum,
koh4hknftnmoney,
koh4compftn,
koh4compftn_entani,
koh4compykzftn,
koh4comptotal,
koh4ykzftnkbn,
ptftnrate,
skykukbn,
tax_taishou,
tax_money,
skygk,
ssu_hknten,
ssu_money,
ssu_tgmoney,
ssu_tgmoney_tax,
sdo_hknten,
sdo_money,
sdo_tgmoney,
sdo_tgmoney_tax,
ztk_hknten,
ztk_money,
ztk_tgmoney,
ztk_tgmoney_tax,
tyk_hknten,
tyk_money,
tyk_tgmoney,
tyk_tgmoney_tax,
csy_hknten,
csy_money,
csy_tgmoney,
csy_tgmoney_tax,
syc_hknten,
syc_money,
syc_tgmoney,
syc_tgmoney_tax,
sjt_hknten,
sjt_money,
sjt_tgmoney,
sjt_tgmoney_tax,
kns_hknten,
kns_money,
kns_tgmoney,
kns_tgmoney_tax,
gzu_hknten,
gzu_money,
gzu_tgmoney,
gzu_tgmoney_tax,
etc_hknten,
etc_money,
etc_tgmoney,
etc_tgmoney_tax,
nyn_hknten,
nyn_money,
nyn_tgmoney,
nyn_tgmoney_tax,
total_hknten,
total_money,
total_tgmoney,
total_tgmoney_tax,
tgmoney_tax_sai,
jihi_1,
jihi_1_tax,
jihi_2,
jihi_2_tax,
jihi_3,
jihi_3_tax,
jihi_4,
jihi_4_tax,
jihi_5,
jihi_5_tax,
jihi_6,
jihi_6_tax,
jihi_7,
jihi_7_tax,
jihi_8,
jihi_8_tax,
jihi_9,
jihi_9_tax,
jihi_10,
jihi_10_tax,
jihi_total,
jihi_total_tax,
jihi_tax,
rjn_ftn,
koh_ftn,
koh_ftn_entani,
ykz_ftn,
rese_ykz_ftn,
kohtaiykzkbn,
chosei,
grp_denpnum,
grp_rennum,
grp_sgkmoney,
secmoney,
hkntekmoney,
discount_kbn,
discount_body,
discount_ratekbn,
discount_teiritu,
discount_rate,
discount_money,
rsishoshin_money,
rsisaishin_money,
rsisdo_money,
rsietc_money,
rsi_tax_sai,
rsi_total,
rsijibai_skymoney,
skymoney_tax_sai,
skymoney,
nyukin_total,
nyukin_kaisu,
misyuriyu,
drcd,
nynshokaisu,
ykzkennum,
skj_ftngaku1,
skj_ftnday1,
skj_ftngaku2,
skj_ftnday2,
skj_ftngaku3,
skj_ftnday3,
saikeisankbn,
ingaishohokbn,
douji_denpnum,
contkbn,
fuku_denpnum,
fuku_kbn,
zaitaku,
kyufugai_shoshin_ten,
kyufugai_sidou_ten,
kyufugai_osin1_ten,
kyufugai_osin2_ten,
kyufugai_osin3_ten,
kyufugai_gokei_ten,
dayinfflg,
acct_updkbn,
jyo_hknftnmoney,
jyo_compftn,
jyo_compftn_entani,
termid,
opid,
creymd,
upymd,
uphms,
msi_hknten,
msi_money,
msi_tgmoney,
msi_tgmoney_tax,
ssn_hknten,
ssn_money,
ssn_tgmoney,
ssn_tgmoney_tax,
hou_hknten,
hou_money,
hou_tgmoney,
hou_tgmoney_tax,
ryo_hknten,
ryo_money,
ryo_tgmoney,
ryo_tgmoney_tax,
shohou_sai,
grp_hakhouflg,
hospnum,
byr_hknten,
byr_money,
byr_tgmoney,
byr_tgmoney_tax,
'0'
from tbl_syunou ;

update tbl_syunou_main set skynyukinkbn = '1'
where skymoney <> nyukin_total ;

ALTER TABLE ONLY tbl_syunou_main
    ADD CONSTRAINT tbl_syunou_main_primary_key PRIMARY KEY (hospnum, nyugaikbn, ptid, denpnum);

CREATE INDEX idx_syunou_main_ptid ON tbl_syunou_main USING btree (hospnum, ptid,sryymd,sryka,skynyukinkbn);

drop table tbl_syunou;

