SRCS = ORCGQ01.CBL \
       ORCGQ02.CBL \
       ORCGQ02A.CBL \
       ORCGQ02B.CBL \
       ORCGQ03.CBL \
       ORCGQ98.CBL \
       ORCGQ99.CBL \
       ORCGQERR.CBL \
       ORCGQID1.CBL \
       ORCGQSUB01.CBL \
       ORCGQSUB02.CBL \
       ORCGQ97.CBL \
       ORCGQ100.CBL \
       ORCGQ96.CBL \
       ORCGQ04.CBL \
       ORCGQSUB03.CBL \
       ORCGQSUB04.CBL \
       ORCGQAPI01.CBL \
       ORCGQAPI01S01.CBL \
       ORCGQAPI01S02.CBL \
       ORCGQAPI01S99.CBL \
       ORCGQAPI02.CBL \
       ORCGQERRMSG.CBL \
       ORCGQ05.CBL \
       ORCGQSUB06.CBL \
       ORCGQAPI03.CBL \
       ORCGQAPI03S01.CBL \
       ORCGQAPI03S02.CBL \

top_builddir = ../..
include $(top_builddir)/cobol/Makefile.global

