SRCS = ORCGR01.CBL \
       ORCGR02.CBL \
       ORCGR03.CBL \
       ORCGR04.CBL \
       ORCGR05.CBL \
       ORCGR06.CBL \
       ORCGR96.CBL \
       ORCGR97.CBL \
       ORCGR98.CBL \
       ORCGR99.CBL \
       ORCGRERR.CBL \
       ORCGRID1.CBL \
       ORCGRID2.CBL \
       ORCGRID3.CBL \
       ORCGRID4.CBL \
       ORAPI042R1V3.CBL \
       ORAPI042R2V3.CBL \

top_builddir = ../..
include $(top_builddir)/cobol/Makefile.global

