SRCS = ORCGL01.CBL \
       ORCGL99.CBL \
       ORCGLERR.CBL \
       ORCGLID1.CBL \
       ORCGLID2.CBL \
       ORCGL03.CBL \
       ORCGL02.CBL \
       ORCGL04.CBL \
       ORCGL06.CBL \
       ORCGL07.CBL \
       ORCGL100.CBL \
       ORAPI051R1V3.CBL \
       ORAPI051R2V3.CBL \

top_builddir = ../..
include $(top_builddir)/cobol/Makefile.global

