SRCS = ORCGI20.CBL \
       ORCGI21.CBL \
       ORCGI22.CBL \
       ORCGI23.CBL \
       ORCGI2ERR.CBL \
       ORCGI2ID1.CBL \
       ORCGI2SUB01.CBL \
       ORCGI2SUB02.CBL \
       ORCGI2SUB03.CBL \
       ORCGI2API01.CBL \
       ORCGI2API01S01.CBL \
       ORCGI2ERRMSG.CBL \

top_builddir = ../..
include $(top_builddir)/cobol/Makefile.global

