\set ON_ERROR_STOP

alter table tbl_ptbyomei alter column ptid type bigint;
alter table tbl_ptbyomei alter column rennum type smallint;
alter table tbl_ptbyomei alter column khnbyomeicd type character varying(7);
alter table tbl_ptbyomei alter column byomeicdsu type smallint;
alter table tbl_ptbyomei alter column byomeicd_1 type character varying(7);
alter table tbl_ptbyomei alter column byomeicd_2 type character varying(7);
alter table tbl_ptbyomei alter column byomeicd_3 type character varying(7);
alter table tbl_ptbyomei alter column byomeicd_4 type character varying(7);
alter table tbl_ptbyomei alter column byomeicd_5 type character varying(7);
alter table tbl_ptbyomei alter column byomeicd_6 type character varying(7);
alter table tbl_ptbyomei alter column byomeicd_7 type character varying(7);
alter table tbl_ptbyomei alter column byomeicd_8 type character varying(7);
alter table tbl_ptbyomei alter column byomeicd_9 type character varying(7);
alter table tbl_ptbyomei alter column byomeicd_10 type character varying(7);
alter table tbl_ptbyomei alter column byomeicd_11 type character varying(7);
alter table tbl_ptbyomei alter column byomeicd_12 type character varying(7);
alter table tbl_ptbyomei alter column byomeicd_13 type character varying(7);
alter table tbl_ptbyomei alter column byomeicd_14 type character varying(7);
alter table tbl_ptbyomei alter column byomeicd_15 type character varying(7);
alter table tbl_ptbyomei alter column byomeicd_16 type character varying(7);
alter table tbl_ptbyomei alter column byomeicd_17 type character varying(7);
alter table tbl_ptbyomei alter column byomeicd_18 type character varying(7);
alter table tbl_ptbyomei alter column byomeicd_19 type character varying(7);
alter table tbl_ptbyomei alter column byomeicd_20 type character varying(7);
alter table tbl_ptbyomei alter column byomeicd_21 type character varying(7);
alter table tbl_ptbyomei alter column manseikbn type smallint;
alter table tbl_ptbyomei alter column hkncombi type smallint;
alter table tbl_ptbyomei alter column rezemm type smallint;
alter table tbl_ptbyomei alter column tenkiymd type character varying(8);
alter table tbl_ptbyomei alter column byomeimoji type smallint;
alter table tbl_ptbyomei alter column chartbyomeimoji type smallint;
alter table tbl_ptbyomei alter column hknnum type character varying(3);
alter table tbl_ptbyomei alter column khnbuicd_1 type character varying(7);
alter table tbl_ptbyomei alter column khnbuicd_2 type character varying(7);
alter table tbl_ptbyomei alter column khnbuicd_3 type character varying(7);
alter table tbl_ptbyomei alter column hospnum type smallint;
