SRCS = ORCGD01.CBL \
       ORCGD02.CBL \
       ORCGD03.CBL \
       ORCGD04.CBL \
       ORCGD05.CBL \
       ORCGDERR.CBL \
       ORCGDID2.CBL \
       ORCGDID1.CBL \
       ORCGD99.CBL  \
       ORCGDSUB01.CBL \
       ORCGDAPI01.CBL \
       ORCGDAPI01S00.CBL \
       ORCGDAPI01S01.CBL \
       ORCGDAPI01S02.CBL \
       ORCGDERRMSG.CBL \
       ORCGDSUB02.CBL \

top_builddir = ../..
include $(top_builddir)/cobol/Makefile.global

