SRCS = ORCGZ01.CBL \
       ORCGZ02.CBL \
       ORCGZ03.CBL \
       ORCGZ04.CBL \
       ORCGZ05.CBL \
       ORCGZ90.CBL \
       ORCGZ98.CBL \
       ORCGZ99.CBL \
       ORCGZERR.CBL \
       ORCGZID1.CBL \
       ORCGZS01.CBL \
       ORCGZ91.CBL \
       ORCGZID2.CBL \
       ORCGZ97.CBL \
       ORCGZ06.CBL \
       ORCGZ07.CBL \
       ORCGZID3.CBL \
       ORCGZS02.CBL \
       ORCGZ08.CBL \
       ORCGZ100.CBL \
       ORAPI102S1V2.CBL \
       ORCGZ010.CBL \

top_builddir = ../..
include $(top_builddir)/cobol/Makefile.global

