SRCS = \
	ORCGI41.CBL \
	ORCGI4ERR.CBL \
	ORCGI4ID1.CBL \
	ORCGI42.CBL \
	ORCGI44.CBL \
	ORCGI47.CBL \
	ORCGI48.CBL \
	ORCGI49.CBL \
	ORCGI411.CBL \
	ORCGI4API01.CBL \
	ORCGI4ID2.CBL \


top_builddir = ../..
include $(top_builddir)/cobol/Makefile.global

