        01  HCM21V06.
            02  HCM21V06-TANJYOG
                        PIC X(2)        OCCURS 3 TIMES.
            02  HCM21V06-NENREI
                        PIC X(3).
            02  HCM21V06-KANANAME
                        PIC X(50).
            02  HCM21V06-NAME
                        PIC X(26).
            02  HCM21V06-NAME2
                        PIC X(50).
            02  HCM21V06-SYOBYOMEI
                        PIC X(44)       OCCURS 5 TIMES.
            02  HCM21V06-KEIKA
                        PIC X(54)       OCCURS 8 TIMES.
            02  HCM21V06-TEKIYO1
                        PIC X(28)       OCCURS 9 TIMES.
            02  HCM21V06-SRYKBN
                        PIC X(2)        OCCURS 30 TIMES.
            02  HCM21V06-TEKIYO2
                        PIC X(52)       OCCURS 30 TIMES.
            02  HCM21V06-TOTALTEN
                        PIC X(6).
            02  HCM21V06-TOTALMONEY
                        PIC X(10).
            02  HCM21V06-SYOKEI
                        PIC X(7).
            02  HCM21V06-SAISINKAISU
                        PIC X(3).
            02  HCM21V06-SHIDOKAISU
                        PIC X(3).
            02  HCM21V06-KOUTEN
                        PIC X(7)        OCCURS 35 TIMES.
            02  HCM21V06-KAISU
                        PIC X(3)        OCCURS 35 TIMES.
            02  HCM21V06-KHNTEN
                        PIC X(7)        OCCURS 19 TIMES.
            02  HCM21V06-RSIIRYOCD
                        PIC X(30).
            02  HCM21V06-HOSPNAME
                        PIC X(90).
            02  HCM21V06-SAIGAIKBN
                        PIC X(8).
            02  HCM21V06-TANJYOY
                        PIC X(2).
            02  HCM21V06-TANJYOM
                        PIC X(2).
            02  HCM21V06-TANJYOD
                        PIC X(2).
            02  HCM21V06-SYOSHIN1
                        PIC X(2).
            02  HCM21V06-SYOSHIN2
                        PIC X(2).
            02  HCM21V06-SYOSHIN3
                        PIC X(2).
            02  HCM21V06-KEIZOKUKANRI
                        PIC X(16).
            02  HCM21V06-KINGAKU
                        PIC X(7)        OCCURS 6 TIMES.
            02  HCM21V06-TENKI
                        PIC X(1).
            02  HCM21V06-SINKEI
                        PIC X(1).
            02  HCM21V06-PTNUM
                        PIC X(20).
            02  HCM21V06-KOFUNUM.
              03  HCM21V06-KOFUNUM-S
                        PIC X(1)        OCCURS 9 TIMES.
            02  HCM21V06-RYOSTYMD.
              03  HCM21V06-RYOSTYMD-S
                        PIC X(1)        OCCURS 6 TIMES.
            02  HCM21V06-RYOEDYMD.
              03  HCM21V06-RYOEDYMD-S
                        PIC X(1)        OCCURS 6 TIMES.
            02  HCM21V06-NISSU.
              03  HCM21V06-NISSU-S
                        PIC X(1)        OCCURS 3 TIMES.
            02  HCM21V06-GOKEI.
              03  HCM21V06-GOKEI-S
                        PIC X(1)        OCCURS 7 TIMES.
            02  HCM21V06-RENNUM
                        PIC X(7).
            02  HCM21V06-KAI
                        PIC X(3).
            02  HCM21V06-PAGE
                        PIC X(5).
            02  HCM21V06-LABEL
                        PIC X(14).
            02  HCM21V06-SYOCD
                        PIC X(5).
            02  HCM21V06-LOPTION
                        PIC X(100).
            02  HCM21V06-TANJYOG2
                        PIC X(2).
            02  HCM21V06-HEAD-G.
              03  HCM21V06-HEAD
                        PIC X(62)       OCCURS 2 TIMES.
