        01  HCM72V01.
            02  HCM72V01-RSIIRYOCD.
              03  HCM72V01-RSIIRYOCD-S
                        PIC X(1)        OCCURS 7 TIMES.
            02  HCM72V01-GOKEI.
              03  HCM72V01-GOKEI-S
                        PIC X(1)        OCCURS 9 TIMES.
            02  HCM72V01-MAISU.
              03  HCM72V01-MAISU-S
                        PIC X(1)        OCCURS 3 TIMES.
            02  HCM72V01-SKYYM.
              03  HCM72V01-SKYG
                        PIC X(1).
              03  HCM72V01-SKYY.
                04  HCM72V01-SKYY-S
                        PIC X(1)        OCCURS 2 TIMES.
              03  HCM72V01-SKYM.
                04  HCM72V01-SKYM-S
                        PIC X(1)        OCCURS 2 TIMES.
            02  HCM72V01-NAME
                        PIC X(50).
            02  HCM72V01-NAME2
                        PIC X(20).
            02  HCM72V01-NINZU
                        PIC X(3).
            02  HCM72V01-PRTYMD.
              03  HCM72V01-PRTYY
                        PIC X(2).
              03  HCM72V01-PRTMM
                        PIC X(2).
              03  HCM72V01-PRTDD
                        PIC X(2).
            02  HCM72V01-HOSPPOST
                        PIC X(8).
            02  HCM72V01-HOSPADRS
                        PIC X(100).
            02  HCM72V01-HOSPNAME
                        PIC X(100).
            02  HCM72V01-KAISETSUNAME
                        PIC X(60).
            02  HCM72V01-HOSPTEL
                        PIC X(15).
            02  HCM72V01-ROUDOUNAME
                        PIC X(8).
            02  HCM72V01-MARK.
              03  HCM72V01-MARK-S
                        PIC X(1)        OCCURS 8 TIMES.
