      *******************************************************************
      * Project code name "ORCA"
      * 日医標準レセプトソフト（JMA standard receipt software）
      * Copyright(C) 2002 JMA (Japan Medical Association)
      *
      * This program is part of "JMA standard receipt software".
      *
      *     This program is distributed in the hope that it will be useful
      * for further advancement in medical care, according to JMA Open
      * Source License, but WITHOUT ANY WARRANTY.
      *     Everyone is granted permission to use, copy, modify and
      * redistribute this program, but only under the conditions described
      * in the JMA Open Source License. You should have received a copy of
      * this license along with this program. If not, stop using this
      * program and contact JMA, 2-28-16 Honkomagome, Bunkyo-ku, Tokyo,
      * 113-8621, Japan.
      ********************************************************************
         02  I4ID1.
              03  I4ID1-ID1CODE.
                04  I4ID1-VALUE  PIC X(10).
              03  I4ID1-ID1MSG.
                04  I4ID1-VALUE  PIC X(80).
              03  I4ID1-B01.
                04  I4ID1-LABEL  PIC X(4).
              03  I4ID1-B12.
                04  I4ID1-LABEL  PIC X(4).
