SRCS = ORCGT01.CBL \
       ORCGT02.CBL \
       ORCGT03.CBL \
       ORCGTERR.CBL \
       ORCGTID1.CBL \
       ORCGTID2.CBL \
       ORCGT99.CBL \
       ORCGT04.CBL \
       ORCGT91.CBL \
       ORCGT05.CBL \
       ORCGT06.CBL \
       ORCGT07.CBL \
       ORCGT08.CBL \
       ORCGT09.CBL \
       ORCGT98.CBL \
       ORCGTID3.CBL \
       ORAPI044R1V3.CBL \
       ORAPI044R2V3.CBL \
       ORAPI044R3V3.CBL \

top_builddir = ../..
include $(top_builddir)/cobol/Makefile.global

