SRCS = ORCGXF01.CBL \
       ORCGXF011.CBL \
       ORCGXF01X.CBL \
       ORCGXFID1.CBL \
       ORCGXFERR.CBL \
       ORCGXFID2.CBL \

top_builddir = ../..
include $(top_builddir)/cobol/Makefile.global

