--                                    --
-- ¼ýÇ¼¹ç·×¥Æ¡¼¥Ö¥ë¤ÎÊÑ¹¹             --
--                                    --
-- ¹àÌÜ¤ÎÄÉ²Ã                         --
--   ¼«Èñ£¶¤«¤é£±£°  JIHI_6           --
--                   JIHI_6_TAX       --
--                   JIHI_7           --
--                   JIHI_7_TAX       --
--                   JIHI_8           --
--                   JIHI_8_TAX       --
--                   JIHI_9           --
--                   JIHI_9_TAX       --
--                   JIHI_10          --
--                   JIHI_10_TAX      --
--   ¸ºÌÈ¶â³Û        DISCOUNT_MONEY   --
--                                    --
-- Create Date : 2005/07/14           --
--                                    --
--

-- TBL_SYUTOTAL_PRV ºï½ü              --

drop table TBL_SYUTOTAL_PRV;

--
-- TBL_SYUTOTAL_PRV ºîÀ®              --

create	table	tbl_syutotal_prv	(
	HOSPID	char(24),
	NYUGAIKBN	char(1),
	PTID	numeric(10,0),
	DENPNUM	numeric(7,0),
	SRYKA	char(2),
	DOUJI_SRYKA1	char(2),
	DOUJI_SRYKA2	char(2),
	DOUJI_SRYKA3	char(2),
	DOUJI_SRYKA4	char(2),
	DOUJI_SRYKA5	char(2),
	DOUJI_SRYKA6	char(2),
	DOUJI_SRYKA7	char(2),
	DOUJI_SRYKA8	char(2),
	DOUJI_SRYKA9	char(2),
	DOUJI_SRYKA10	char(2),
	SRYYMD	char(8),
	DENPJTIKBN	char(1),
	CREATEKBN	char(1),
	DENPPRTYMD	char(8),
	SKYSTYMD	char(8),
	SKYEDYMD	char(8),
	HKNCOMBINUM	char(4),
	SYUHKNNUM	char(3),
	SYUHKNFTNMONEY	numeric(7,0),
	SYUCOMPFTN	numeric(7,0),
	SYUCOMPFTN_ENTANI	numeric(8,1),
	SYUCOMPYKZFTN	numeric(7,0),
	SYUCOMPTOTAL	numeric(7,0),
	SYUYKZFTNKBN	char(1),
	KOH1HKNNUM	char(3),
	KOH1HKNFTNMONEY	numeric(7,0),
	KOH1COMPFTN	numeric(7,0),
	KOH1COMPFTN_ENTANI	numeric(8,1),
	KOH1COMPYKZFTN	numeric(7,0),
	KOH1COMPTOTAL	numeric(7,0),
	KOH1YKZFTNKBN	char(1),
	KOH2HKNNUM	char(3),
	KOH2HKNFTNMONEY	numeric(7,0),
	KOH2COMPFTN	numeric(7,0),
	KOH2COMPFTN_ENTANI	numeric(8,1),
	KOH2COMPYKZFTN	numeric(7,0),
	KOH2COMPTOTAL	numeric(7,0),
	KOH2YKZFTNKBN	char(1),
	KOH3HKNNUM	char(3),
	KOH3HKNFTNMONEY	numeric(7,0),
	KOH3COMPFTN	numeric(7,0),
	KOH3COMPFTN_ENTANI	numeric(8,1),
	KOH3COMPYKZFTN	numeric(7,0),
	KOH3COMPTOTAL	numeric(7,0),
	KOH3YKZFTNKBN	char(1),
	KOH4HKNNUM	char(3),
	KOH4HKNFTNMONEY	numeric(7,0),
	KOH4COMPFTN	numeric(7,0),
	KOH4COMPFTN_ENTANI	numeric(8,1),
	KOH4COMPYKZFTN	numeric(7,0),
	KOH4COMPTOTAL	numeric(7,0),
	KOH4YKZFTNKBN	char(1),
	PTFTNRATE	numeric(3,0),
	SKYKUKBN	char(1),
	SSU_HKNTEN	numeric(7,0),
	SSU_MONEY	numeric(7,0),
	SSU_TGMONEY	numeric(7,0),
	SSU_TGMONEY_TAX	numeric(7,0),
	SDO_HKNTEN	numeric(7,0),
	SDO_MONEY	numeric(7,0),
	SDO_TGMONEY	numeric(7,0),
	SDO_TGMONEY_TAX	numeric(7,0),
	ZTK_HKNTEN	numeric(7,0),
	ZTK_MONEY	numeric(7,0),
	ZTK_TGMONEY	numeric(7,0),
	ZTK_TGMONEY_TAX	numeric(7,0),
	TYK_HKNTEN	numeric(7,0),
	TYK_MONEY	numeric(7,0),
	TYK_TGMONEY	numeric(7,0),
	TYK_TGMONEY_TAX	numeric(7,0),
	CSY_HKNTEN	numeric(7,0),
	CSY_MONEY	numeric(7,0),
	CSY_TGMONEY	numeric(7,0),
	CSY_TGMONEY_TAX	numeric(7,0),
	SYC_HKNTEN	numeric(7,0),
	SYC_MONEY	numeric(7,0),
	SYC_TGMONEY	numeric(7,0),
	SYC_TGMONEY_TAX	numeric(7,0),
	SJT_HKNTEN	numeric(7,0),
	SJT_MONEY	numeric(7,0),
	SJT_TGMONEY	numeric(7,0),
	SJT_TGMONEY_TAX	numeric(7,0),
	KNS_HKNTEN	numeric(7,0),
	KNS_MONEY	numeric(7,0),
	KNS_TGMONEY	numeric(7,0),
	KNS_TGMONEY_TAX	numeric(7,0),
	GZU_HKNTEN	numeric(7,0),
	GZU_MONEY	numeric(7,0),
	GZU_TGMONEY	numeric(7,0),
	GZU_TGMONEY_TAX	numeric(7,0),
	ETC_HKNTEN	numeric(7,0),
	ETC_MONEY	numeric(7,0),
	ETC_TGMONEY	numeric(7,0),
	ETC_TGMONEY_TAX	numeric(7,0),
	NYN_HKNTEN	numeric(7,0),
	NYN_MONEY	numeric(7,0),
	NYN_TGMONEY	numeric(7,0),
	NYN_TGMONEY_TAX	numeric(7,0),
	TOTAL_HKNTEN	numeric(7,0),
	TOTAL_MONEY	numeric(7,0),
	TOTAL_TGMONEY	numeric(7,0),
	TOTAL_TGMONEY_TAX	numeric(7,0),
	TGMONEY_TAX_SAI	numeric(7,0),
	JIHI_1	numeric(7,0),
	JIHI_1_TAX	numeric(7,0),
	JIHI_2	numeric(7,0),
	JIHI_2_TAX	numeric(7,0),
	JIHI_3	numeric(7,0),
	JIHI_3_TAX	numeric(7,0),
	JIHI_4	numeric(7,0),
	JIHI_4_TAX	numeric(7,0),
	JIHI_5	numeric(7,0),
	JIHI_5_TAX	numeric(7,0),
	JIHI_6	numeric(7,0),
	JIHI_6_TAX	numeric(7,0),
	JIHI_7	numeric(7,0),
	JIHI_7_TAX	numeric(7,0),
	JIHI_8	numeric(7,0),
	JIHI_8_TAX	numeric(7,0),
	JIHI_9	numeric(7,0),
	JIHI_9_TAX	numeric(7,0),
	JIHI_10	numeric(7,0),
	JIHI_10_TAX	numeric(7,0),
	JIHI_TOTAL	numeric(7,0),
	JIHI_TOTAL_TAX	numeric(7,0),
	JIHI_TAX	numeric(7,0),
	RJN_FTN	numeric(7,0),
	KOH_FTN	numeric(7,0),
	KOH_FTN_ENTANI	numeric(8,1),
	CHOSEI	numeric(7,0),
	GRP_SGKMONEY	numeric(7,0),
	HKNTEKMONEY	numeric(7,0),
	DISCOUNT_KBN	char(2),
	DISCOUNT_BODY	varchar(160),
	DISCOUNT_RATEKBN	char(2),
	DISCOUNT_TEIRITU	char(1),
	DISCOUNT_RATE	numeric(7,0),
	DISCOUNT_MONEY	numeric(7,0),
	RSISHOSHIN_MONEY	numeric(7,0),
	RSISAISHIN_MONEY	numeric(7,0),
	RSISDO_MONEY	numeric(7,0),
	RSIETC_MONEY	numeric(7,0),
	RSI_TAX_SAI	numeric(7,0),
	RSI_TOTAL	numeric(7,0),
	RSIJIBAI_SKYMONEY	numeric(7,0),
	SKYMONEY_TAX_SAI	numeric(7,0),
	SKYMONEY	numeric(7,0),
	NYUKIN_TOTAL	numeric(7,0),
	NYUKIN_KAISU	numeric(7,0),
	MISYURIYU	char(2),
	ZAITAKU	char(1),
	KYUFUGAI_SHOSHIN_TEN	numeric(7,0),
	KYUFUGAI_SIDOU_TEN	numeric(7,0),
	KYUFUGAI_OSIN1_TEN	numeric(7,0),
	KYUFUGAI_OSIN2_TEN	numeric(7,0),
	KYUFUGAI_OSIN3_TEN	numeric(7,0),
	KYUFUGAI_GOKEI_TEN	numeric(7,0),
	TERMID	varchar(16),
	OPID	varchar(16),
	CREYMD	char(8),
	UPYMD	char(8),
	UPHMS	char(6),
	primary	key(
		HOSPID,
		NYUGAIKBN,
		PTID,
		DENPNUM,
		CREYMD
	)
);
