SRCS = ORCGI01.CBL \
       ORCGI02.CBL \
       ORCGI03.CBL \
       ORCGI04.CBL \
       ORCGI041.CBL \
       ORCGI05.CBL \
       ORCGI06.CBL \
       ORCGI0ERR.CBL \
       ORCGI0ID1.CBL \
       ORCGI0ID2.CBL \
       ORCGI0SUB01.CBL \
       ORCGI0SUB02.CBL \
       ORCGI0SUB03.CBL \
       ORCGI0API01.CBL \
       ORCGI0API02.CBL \
	   ORCGI4API02.CBL \
	   ORCGI4API03.CBL \

top_builddir = ../..
include $(top_builddir)/cobol/Makefile.global

