SRCS = ORCGM00.CBL \
       ORCGM01.CBL \
       ORCGM01N.CBL \
       ORCGM02.CBL \
       ORCGM95.CBL \
       ORCGMID1.CBL \
       ORCGMERR.CBL \
       ORCGMVER.CBL \
       ORCGM98.CBL \
       ORCGMUID.CBL \
       ORCGM99.CBL \
       ORCGMID2.CBL \
       ORCGMDAS.CBL \
       ORCGMLOG.CBL \
       ORCGMINF.CBL \
       ORCGMPRT.CBL \

top_builddir = ../..
include $(top_builddir)/cobol/Makefile.global

