SRCS = ORCGG01.CBL \
       ORCGG99.CBL \
       ORCGGERR.CBL \
       ORCGGID1.CBL \
       ORCGGID2.CBL \
       ORCGG02.CBL \
       ORCGG03.CBL \
       ORCGG05.CBL \
       ORCGG07.CBL \
       ORCGG100.CBL \
       ORAPI052R1V3.CBL \
       ORAPI052R2V3.CBL \
       ORAPI052R3V3.CBL \
       ORAPI052R4V3.CBL \
       ORAPI052R5V3.CBL \
       ORAPI052R6V3.CBL \
       ORAPI052R7V3.CBL \
       ORAPI052R8V3.CBL \
       ORAPI052R9V3.CBL \
       ORAPI052R9V3S00.CBL \
       ORAPI052R9V3S01.CBL \
       ORAPI052R9V3S02.CBL \

top_builddir = ../..
include $(top_builddir)/cobol/Makefile.global

