SRCS = ORCGX01.CBL \
       ORCGX02.CBL \
       ORCGX03.CBL \
       ORCGX04.CBL \
       ORCGX05.CBL \
       ORCGX06.CBL \
       ORCGX07.CBL \
       ORCGX91.CBL \
       ORCGX97.CBL \
       ORCGX98.CBL \
       ORCGX99.CBL \
       ORCGX100.CBL \
       ORCGXERR.CBL \
       ORCGXID1.CBL \
       ORCGXID2.CBL \
       ORCHXLST.CBL \
       ORCGXSUB01.CBL \
       ORCGX08.CBL \

top_builddir = ../..
include $(top_builddir)/cobol/Makefile.global

