SRCS = ORCGJ02.CBL \
       ORCGJ021.CBL \
       ORCGJ022.CBL \
       ORCGJ03.CBL \
       ORCGJ04.CBL \
       ORCGJ041.CBL \
       ORCGJ042.CBL \
       ORCGJ98.CBL \
       ORCGJ99.CBL \
       ORCGJERR.CBL \
       ORCGJID1.CBL \
       ORCGJ025.CBL \
       ORCGJ026.CBL \
       ORCGJID2.CBL \
       ORCGJERR2.CBL \

top_builddir = ../..
include $(top_builddir)/cobol/Makefile.global

