SRCS = ORCGXGID1.CBL \
       ORCGXGERR.CBL \
       ORCGXG99.CBL \
       ORCGXG02.CBL \
       ORCGXG01.CBL \
       ORCGXG03.CBL \
       ORCGXG04.CBL \

top_builddir = ../..
include $(top_builddir)/cobol/Makefile.global

