create	table	tbl_prvkanri	(
	TBL_KEY	char(8),
	RENNUM	numeric(4,0),
	TBL_GROUP	char(14),
	SHORI_RENNUM	numeric(4,0),
	SHELLID	varchar(20),
	PRTID	varchar(20),
	SRYYM	varchar(6),
	SKYYMD	varchar(8),
	PTID	numeric(10,0),
	PAGE	numeric(5,0),
	MOD_FLG	char(1),
	SHORI_MOD_FLG	char(1),
	FILENAME	varchar(200),
	TITLE	varchar(100),
	PRTNM	varchar(16),
	PTNUM	varchar(20),
	MEMO	varchar(100),
	RECE_FLG	numeric(4),
	SHORI_KBN	char(1),
	TBL_GROUP1	char(14),
	TBL_GROUP2	char(14),
	TBL_GROUP3	char(14),
	TBL_GROUP4	char(14),
	TBL_GROUP5	char(14),
	TERMID	varchar(32),
	OPID	varchar(16),
	CREYMD	varchar(8),
	UPYMD	varchar(8),
	UPHMS	varchar(6),
	primary	key(
		TBL_KEY,
		RENNUM,
		TBL_GROUP,
		SHORI_RENNUM,
		PAGE
	)
);
