SRCS = ORCGO01.CBL \
       ORCGO02.CBL \
       ORCGO03.CBL \
       ORCGO04.CBL \
       ORCGO05.CBL \
       ORCGO99.CBL \
       ORCGOERR.CBL \
       ORCGOID1.CBL \
       ORCGOID2.CBL \
       ORCGOID3.CBL 

top_builddir = ../..
include $(top_builddir)/cobol/Makefile.global

