--                                    --
-- ワーク診療行為マスタ               --
--    ドクターコード                  --
--    更新中フラグ                    --
--    電子カルテフラグ                --
--    電子カルテキー の追加           --
--                                    --
--   ドクターコード(DRCD)             --
--   更新中フラグ(MOD_FLG)            --
--   電子カルテフラグ(KARTE_FLG)      --
--   電子カルテキー(KARTE_KEY) の追加 --
--                                    --
-- Create Date : 2003/08/05           --
--                                    --

-- TBL_WKSRYACTWK  作成               --

create table TBL_WKSRYACTWK (
hospid			 character(24) NOT NULL,
nyugaikbn		 character(1) NOT NULL,
ptid			 numeric(10,0) NOT NULL,
sryka			 character(2) NOT NULL,
sryymd			 character(8) NOT NULL,
hkncombi		 numeric(4,0) NOT NULL,
zainum			 numeric(8,0) NOT NULL,
rennum			 numeric(2,0) NOT NULL,
srysyukbn		 character(3),
srykbn			 character(2),
jihimoneytotal		 numeric(7,0) DEFAULT 0,
srycd_1			 character(9),
srysuryo_1		 numeric(8,3) DEFAULT 0,
srykaisu_1		 numeric(3,0) DEFAULT 0,
zaikaisu_1		 numeric(8,0) DEFAULT 0,
autokbn_1		 character(1),
inputnum_1		 numeric(3,0) DEFAULT 0,
inputcoment_1		 character varying(80),
inputchi1_1		 character(8),
inputchi1_2		 character(8),
inputchi1_3		 character(8),
inputchi1_4		 character(8),
inputcd_1		 character(22),
jihimoney_1		 numeric(7,0) DEFAULT 0,
srycd_2			 character(9),
srysuryo_2		 numeric(8,3) DEFAULT 0,
srykaisu_2		 numeric(3,0) DEFAULT 0,
zaikaisu_2		 numeric(8,0) DEFAULT 0,
autokbn_2		 character(1),
inputnum_2		 numeric(3,0) DEFAULT 0,
inputcoment_2		 character varying(80),
inputchi2_1		 character(8),
inputchi2_2		 character(8),
inputchi2_3		 character(8),
inputchi2_4		 character(8),
inputcd_2		 character(22),
jihimoney_2		 numeric(7,0) DEFAULT 0,
srycd_3			 character(9),
srysuryo_3		 numeric(8,3) DEFAULT 0,
srykaisu_3		 numeric(3,0) DEFAULT 0,
zaikaisu_3		 numeric(8,0) DEFAULT 0,
autokbn_3		 character(1),
inputnum_3		 numeric(3,0) DEFAULT 0,
inputcoment_3		 character varying(80),
inputchi3_1		 character(8),
inputchi3_2		 character(8),
inputchi3_3		 character(8),
inputchi3_4		 character(8),
inputcd_3		 character(22),
jihimoney_3		 numeric(7,0) DEFAULT 0,
srycd_4			 character(9),
srysuryo_4		 numeric(8,3) DEFAULT 0,
srykaisu_4		 numeric(3,0) DEFAULT 0,
zaikaisu_4		 numeric(8,0) DEFAULT 0,
autokbn_4		 character(1),
inputnum_4		 numeric(3,0) DEFAULT 0,
inputcoment_4		 character varying(80),
inputchi4_1		 character(8),
inputchi4_2		 character(8),
inputchi4_3		 character(8),
inputchi4_4		 character(8),
inputcd_4		 character(22),
jihimoney_4		 numeric(7,0) DEFAULT 0,
srycd_5			 character(9),
srysuryo_5		 numeric(8,3) DEFAULT 0,
srykaisu_5		 numeric(3,0) DEFAULT 0,
zaikaisu_5		 numeric(8,0) DEFAULT 0,
autokbn_5		 character(1),
inputnum_5		 numeric(3,0) DEFAULT 0,
inputcoment_5		 character varying(80),
inputchi5_1		 character(8),
inputchi5_2		 character(8),
inputchi5_3		 character(8),
inputchi5_4		 character(8),
inputcd_5		 character(22),
jihimoney_5		 numeric(7,0) DEFAULT 0,
zaitenkei		 numeric(8,0) DEFAULT 0,
zaikaikei		 numeric(7,0) DEFAULT 0,
syuten1			 numeric(7,0) DEFAULT 0,
syuten2			 numeric(7,0) DEFAULT 0,
ykzten			 numeric(7,0) DEFAULT 0,
kizaiten		 numeric(7,0) DEFAULT 0,
douji_denpnum		 numeric(7,0) DEFAULT 0,
douji_rennum		 numeric(1,0) DEFAULT 0,
contkbn			 character(1),
termid			 character varying(16),
opid			 character varying(16),
creymd			 character(8),
upymd			 character(8),
uphms			 character(6),
Constraint "tbl_wksryactwk_primary_key" Primary Key ("hospid", "nyugaikbn", "ptid", "sryka", "sryymd", "hkncombi", "zainum", "rennum")
);
-- TBL_WKSRYACT → TBL_WKSRYACTWK   --

insert into TBL_WKSRYACTWK
select * from TBL_WKSRYACT;

-- TBL_WKSRYACT 削除                --

drop table TBL_WKSRYACT;

-- TBL_WKSRYACT 作成                --

create table TBL_WKSRYACT (
hospid			 character(24) NOT NULL,
nyugaikbn		 character(1) NOT NULL,
ptid			 numeric(10,0) NOT NULL,
sryka			 character(2) NOT NULL,
sryymd			 character(8) NOT NULL,
hkncombi		 numeric(4,0) NOT NULL,
zainum			 numeric(8,0) NOT NULL,
rennum			 numeric(2,0) NOT NULL,
drcd			 character(5),
srysyukbn		 character(3),
srykbn			 character(2),
jihimoneytotal		 numeric(7,0) DEFAULT 0,
srycd_1			 character(9),
srysuryo_1		 numeric(8,3) DEFAULT 0,
srykaisu_1		 numeric(3,0) DEFAULT 0,
zaikaisu_1		 numeric(8,0) DEFAULT 0,
autokbn_1		 character(1),
inputnum_1		 numeric(3,0) DEFAULT 0,
inputcoment_1		 character varying(80),
inputchi1_1		 character(8),
inputchi1_2		 character(8),
inputchi1_3		 character(8),
inputchi1_4		 character(8),
inputcd_1		 character(22),
jihimoney_1		 numeric(7,0) DEFAULT 0,
srycd_2			 character(9),
srysuryo_2		 numeric(8,3) DEFAULT 0,
srykaisu_2		 numeric(3,0) DEFAULT 0,
zaikaisu_2		 numeric(8,0) DEFAULT 0,
autokbn_2		 character(1),
inputnum_2		 numeric(3,0) DEFAULT 0,
inputcoment_2		 character varying(80),
inputchi2_1		 character(8),
inputchi2_2		 character(8),
inputchi2_3		 character(8),
inputchi2_4		 character(8),
inputcd_2		 character(22),
jihimoney_2		 numeric(7,0) DEFAULT 0,
srycd_3			 character(9),
srysuryo_3		 numeric(8,3) DEFAULT 0,
srykaisu_3		 numeric(3,0) DEFAULT 0,
zaikaisu_3		 numeric(8,0) DEFAULT 0,
autokbn_3		 character(1),
inputnum_3		 numeric(3,0) DEFAULT 0,
inputcoment_3		 character varying(80),
inputchi3_1		 character(8),
inputchi3_2		 character(8),
inputchi3_3		 character(8),
inputchi3_4		 character(8),
inputcd_3		 character(22),
jihimoney_3		 numeric(7,0) DEFAULT 0,
srycd_4			 character(9),
srysuryo_4		 numeric(8,3) DEFAULT 0,
srykaisu_4		 numeric(3,0) DEFAULT 0,
zaikaisu_4		 numeric(8,0) DEFAULT 0,
autokbn_4		 character(1),
inputnum_4		 numeric(3,0) DEFAULT 0,
inputcoment_4		 character varying(80),
inputchi4_1		 character(8),
inputchi4_2		 character(8),
inputchi4_3		 character(8),
inputchi4_4		 character(8),
inputcd_4		 character(22),
jihimoney_4		 numeric(7,0) DEFAULT 0,
srycd_5			 character(9),
srysuryo_5		 numeric(8,3) DEFAULT 0,
srykaisu_5		 numeric(3,0) DEFAULT 0,
zaikaisu_5		 numeric(8,0) DEFAULT 0,
autokbn_5		 character(1),
inputnum_5		 numeric(3,0) DEFAULT 0,
inputcoment_5		 character varying(80),
inputchi5_1		 character(8),
inputchi5_2		 character(8),
inputchi5_3		 character(8),
inputchi5_4		 character(8),
inputcd_5		 character(22),
jihimoney_5		 numeric(7,0) DEFAULT 0,
zaitenkei		 numeric(8,0) DEFAULT 0,
zaikaikei		 numeric(7,0) DEFAULT 0,
syuten1			 numeric(7,0) DEFAULT 0,
syuten2			 numeric(7,0) DEFAULT 0,
ykzten			 numeric(7,0) DEFAULT 0,
kizaiten		 numeric(7,0) DEFAULT 0,
douji_denpnum		 numeric(7,0) DEFAULT 0,
douji_rennum		 numeric(1,0) DEFAULT 0,
contkbn			 character(1),
mod_flg			 numeric(1,0) DEFAULT 0,
karte_flg		 numeric(1,0) DEFAULT 0,
karte_key		 character varying(36),
termid			 character varying(16),
opid			 character varying(16),
creymd			 character(8),
upymd			 character(8),
uphms			 character(6),
Constraint "tbl_wksryact_primary_key" Primary Key ("hospid", "nyugaikbn", "ptid", "sryka", "sryymd", "hkncombi", "zainum", "rennum")
);

-- TBL_WKSRYACTWK → TBL_WKSRYACT   --

insert into TBL_WKSRYACT
(hospid,
nyugaikbn,
ptid,
sryka,
sryymd,
hkncombi,
zainum,
rennum,
drcd,
srysyukbn,
srykbn,
jihimoneytotal,
srycd_1,
srysuryo_1,
srykaisu_1,
zaikaisu_1,
autokbn_1,
inputnum_1,
inputcoment_1,
inputchi1_1,
inputchi1_2,
inputchi1_3,
inputchi1_4,
inputcd_1,
jihimoney_1,
srycd_2,
srysuryo_2,
srykaisu_2,
zaikaisu_2,
autokbn_2,
inputnum_2,
inputcoment_2,
inputchi2_1,
inputchi2_2,
inputchi2_3,
inputchi2_4,
inputcd_2,
jihimoney_2,
srycd_3,
srysuryo_3,
srykaisu_3,
zaikaisu_3,
autokbn_3,
inputnum_3,
inputcoment_3,
inputchi3_1,
inputchi3_2,
inputchi3_3,
inputchi3_4,
inputcd_3,
jihimoney_3,
srycd_4,
srysuryo_4,
srykaisu_4,
zaikaisu_4,
autokbn_4,
inputnum_4,
inputcoment_4,
inputchi4_1,
inputchi4_2,
inputchi4_3,
inputchi4_4,
inputcd_4,
jihimoney_4,
srycd_5,
srysuryo_5,
srykaisu_5,
zaikaisu_5,
autokbn_5,
inputnum_5,
inputcoment_5,
inputchi5_1,
inputchi5_2,
inputchi5_3,
inputchi5_4,
inputcd_5,
jihimoney_5,
zaitenkei,
zaikaikei,
syuten1,
syuten2,
ykzten,
kizaiten,
douji_denpnum,
douji_rennum,
contkbn,
mod_flg,
karte_flg,
karte_key,
termid,
opid,
creymd,
upymd,
uphms
)
select
hospid,
nyugaikbn,
ptid,
sryka,
sryymd,
hkncombi,
zainum,
rennum,
'     ',
srysyukbn,
srykbn,
jihimoneytotal,
srycd_1,
srysuryo_1,
srykaisu_1,
zaikaisu_1,
autokbn_1,
inputnum_1,
inputcoment_1,
inputchi1_1,
inputchi1_2,
inputchi1_3,
inputchi1_4,
inputcd_1,
jihimoney_1,
srycd_2,
srysuryo_2,
srykaisu_2,
zaikaisu_2,
autokbn_2,
inputnum_2,
inputcoment_2,
inputchi2_1,
inputchi2_2,
inputchi2_3,
inputchi2_4,
inputcd_2,
jihimoney_2,
srycd_3,
srysuryo_3,
srykaisu_3,
zaikaisu_3,
autokbn_3,
inputnum_3,
inputcoment_3,
inputchi3_1,
inputchi3_2,
inputchi3_3,
inputchi3_4,
inputcd_3,
jihimoney_3,
srycd_4,
srysuryo_4,
srykaisu_4,
zaikaisu_4,
autokbn_4,
inputnum_4,
inputcoment_4,
inputchi4_1,
inputchi4_2,
inputchi4_3,
inputchi4_4,
inputcd_4,
jihimoney_4,
srycd_5,
srysuryo_5,
srykaisu_5,
zaikaisu_5,
autokbn_5,
inputnum_5,
inputcoment_5,
inputchi5_1,
inputchi5_2,
inputchi5_3,
inputchi5_4,
inputcd_5,
jihimoney_5,
zaitenkei,
zaikaikei,
syuten1,
syuten2,
ykzten,
kizaiten,
douji_denpnum,
douji_rennum,
contkbn,
0,
0,
' ',
termid,
opid,
creymd,
upymd,
uphms
from TBL_WKSRYACTWK;


-- TBL_WKSRYACTWK 削除             --

drop table TBL_WKSRYACTWK;
