create	table	tbl_qrcdhkn	(
	HOSPID	char(24),
	REGISTYMD	char(8),
	REGISTID	numeric(5,0),
	REGISTTIME	char(6),
	SEIDOKBN	char(3),
	HKNJANUM	char(8),
	KIGONUM	varchar(40),
	HONKZKKBN	char(1),
	KANANAME	varchar(100),
	SEX	char(1),
	BIRTHDAY	char(7),
	KANRINUM	varchar(100),
	NAME	varchar(100),
	KYURATE	varchar(2),
	SAIHAKKU	varchar(50),
	PTID	numeric(10,0),
	KIGO	varchar(80),
	NUM	varchar(80),
	BIRTHDAYS	char(8),
	ERRCD	char(2),
	MOD_FLG	numeric(1,0),
	MOD_FLG2	numeric(1,0),
	DELKBN	char(1),
	TERMID	varchar(64),
	OPID	varchar(16),
	CREYMD	char(8),
	UPYMD	char(8),
	UPHMS	char(6),
	primary	key(
		HOSPID,
		REGISTYMD,
		REGISTID
	)
);
